import React, { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useLocation, useNavigate } from 'react-router-dom';
import { LiaBoxesSolid, LiaChartPieSolid, LiaClipboardListSolid, LiaExchangeAltSolid, LiaPlusSolid, LiaStoreAltSolid, LiaTruckLoadingSolid } from 'react-icons/lia';
import { firestore } from '../../firebase';
import { AdministrativeCommandService, AdministrativeDataTable, AdministrativeEmptyState, AdministrativeModuleLayout, PermissionGate } from '../administrative-core';
import './inventory.css';

const NAVIGATION = [
    { label: 'ALMOXARIFADO', items: [
        { label: 'Visão geral', path: '/admin/almoxarifado', end: true, icon: LiaChartPieSolid },
        { label: 'Produtos', path: '/admin/almoxarifado/produtos', icon: LiaBoxesSolid },
        { label: 'Depósitos', path: '/admin/almoxarifado/depositos', icon: LiaStoreAltSolid },
        { label: 'Nova entrada', path: '/admin/almoxarifado/entrada', icon: LiaTruckLoadingSolid },
        { label: 'Movimentações', path: '/admin/almoxarifado/movimentacoes', icon: LiaExchangeAltSolid },
        { label: 'Requisições', path: '/admin/almoxarifado/requisicoes', icon: LiaClipboardListSolid },
    ] },
];
const REQUEST_STATUS = { requested: 'Solicitado', awaiting_authorization: 'Aguardando autorização', authorized: 'Autorizado', separating: 'Em separação', delivered: 'Entregue', received: 'Recebido', cancelled: 'Cancelado' };
const MOVEMENT_TYPES = { entry: 'Entrada', exit: 'Saída', transfer: 'Transferência', return: 'Devolução', adjustment: 'Ajuste', loss: 'Perda' };
const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const dateLabel = value => value?.toDate?.().toLocaleString('pt-BR') || '—';

function useCollection(name) {
    const [state, setState] = useState({ loading: true, rows: [], error: '' });
    useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snapshot => setState({ loading: false, rows: snapshot.docs.map(item => ({ id: item.id, ...item.data() })), error: '' }), error => setState({ loading: false, rows: [], error: error.message })), [name]);
    return state;
}
const Empty = ({ title, description, action }) => <AdministrativeEmptyState icon={LiaBoxesSolid} title={title} description={description} action={action} />;
const Field = ({ label, children, full = false }) => <label className={full ? 'full' : ''}><span>{label}</span>{children}</label>;

function Dashboard({ products, movements, requests }) {
    const lowStock = products.filter(item => Number(item.currentStock || 0) <= Number(item.minimumStock || 0));
    const stockValue = products.reduce((sum, item) => sum + Number(item.currentStock || 0) * Number(item.averageValue || 0), 0);
    const month = new Date().getMonth(); const recentMovements = movements.filter(item => item.createdAt?.toDate?.().getMonth() === month);
    return <>
        <section className="inventory-metrics"><article><strong>{products.length}</strong><span>Itens cadastrados</span></article><article><strong>{money(stockValue)}</strong><span>Valor estimado</span></article><article><strong>{recentMovements.filter(item => item.type === 'entry').length}</strong><span>Entradas no mês</span></article><article><strong>{recentMovements.filter(item => item.type === 'exit').length}</strong><span>Saídas no mês</span></article><article className={lowStock.length ? 'warning' : ''}><strong>{lowStock.length}</strong><span>Abaixo do mínimo</span></article><article><strong>{requests.filter(item => !['received', 'cancelled'].includes(item.status)).length}</strong><span>Requisições pendentes</span></article></section>
        <div className="inventory-dashboard-grid"><section className="data-card inventory-card"><h2>Estoque baixo</h2>{lowStock.length ? lowStock.slice(0, 8).map(item => <div className="inventory-alert" key={item.id}><span>{item.description}</span><strong>{item.currentStock} {item.unit}</strong></div>) : <p className="inventory-muted">Nenhum produto abaixo do estoque mínimo.</p>}</section><section className="data-card inventory-card"><h2>Últimas movimentações</h2>{movements.length ? movements.slice(0, 8).map(item => <div className="inventory-alert" key={item.id}><span>{MOVEMENT_TYPES[item.type]} · {item.productDescription}</span><strong>{item.quantity}</strong></div>) : <p className="inventory-muted">Nenhuma movimentação registrada.</p>}</section></div>
    </>;
}

function Products({ rows }) {
    const [open, setOpen] = useState(false); const [form, setForm] = useState({ code: '', description: '', category: '', unit: 'UN', brand: '', minimumStock: 0, maximumStock: 0 }); const [message, setMessage] = useState('');
    const submit = async event => { event.preventDefault(); setMessage('Salvando...'); try { await AdministrativeCommandService.run('almoxarifado', 'createProduct', form); setForm({ code: '', description: '', category: '', unit: 'UN', brand: '', minimumStock: 0, maximumStock: 0 }); setOpen(false); setMessage('Produto cadastrado.'); } catch (error) { setMessage(error.message); } };
    return <section className="data-card inventory-card"><div className="inventory-heading"><div><h2>Produtos</h2><p>{rows.length} item(ns) cadastrado(s).</p></div><PermissionGate permission="almoxarifado.gerenciar"><button className="primary-button" onClick={() => setOpen(value => !value)}><LiaPlusSolid /> Novo produto</button></PermissionGate></div>{message && <p className="inventory-feedback">{message}</p>}{open && <form className="inventory-form" onSubmit={submit}><Field label="Código *"><input required value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></Field><Field label="Descrição *"><input required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field><Field label="Categoria"><input value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /></Field><Field label="Unidade *"><input required value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} /></Field><Field label="Marca"><input value={form.brand} onChange={e => setForm({ ...form, brand: e.target.value })} /></Field><Field label="Estoque mínimo"><input type="number" min="0" value={form.minimumStock} onChange={e => setForm({ ...form, minimumStock: e.target.value })} /></Field><Field label="Estoque máximo"><input type="number" min="0" value={form.maximumStock} onChange={e => setForm({ ...form, maximumStock: e.target.value })} /></Field><div className="full inventory-actions"><button className="primary-button">Cadastrar</button></div></form>}
        <AdministrativeDataTable rows={rows} columns={[{ key: 'code', label: 'Código' }, { key: 'description', label: 'Descrição' }, { key: 'category', label: 'Categoria' }, { key: 'unit', label: 'Unidade' }, { key: 'currentStock', label: 'Estoque' }, { key: 'minimumStock', label: 'Mínimo' }, { key: 'averageValue', label: 'Valor médio', render: row => money(row.averageValue) }]} empty={<Empty title="Nenhum produto cadastrado" description="Cadastre os materiais controlados pelo almoxarifado." />} />
    </section>;
}

function Warehouses({ rows }) {
    const [form, setForm] = useState({ name: '', code: '', location: '', responsibleName: '' }); const [message, setMessage] = useState('');
    const submit = async event => { event.preventDefault(); try { await AdministrativeCommandService.run('almoxarifado', 'createWarehouse', form); setForm({ name: '', code: '', location: '', responsibleName: '' }); setMessage('Depósito cadastrado.'); } catch (error) { setMessage(error.message); } };
    return <div className="inventory-two-columns"><PermissionGate permission="almoxarifado.gerenciar"><form className="data-card inventory-card inventory-form single" onSubmit={submit}><h2>Novo depósito</h2><Field label="Nome *"><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="Código *"><input required value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></Field><Field label="Localização"><input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></Field><Field label="Responsável"><input value={form.responsibleName} onChange={e => setForm({ ...form, responsibleName: e.target.value })} /></Field>{message && <p>{message}</p>}<button className="primary-button">Cadastrar depósito</button></form></PermissionGate><section className="data-card inventory-card"><h2>Depósitos</h2><AdministrativeDataTable rows={rows} columns={[{ key: 'code', label: 'Código' }, { key: 'name', label: 'Nome' }, { key: 'location', label: 'Localização' }, { key: 'responsibleName', label: 'Responsável' }]} empty={<Empty title="Nenhum depósito cadastrado" description="Defina os locais físicos de armazenamento." />} /></section></div>;
}

function MovementForm({ products, warehouses, defaultType = 'entry' }) {
    const navigate = useNavigate(); const [form, setForm] = useState({ type: defaultType, productId: '', warehouseId: '', destinationWarehouseId: '', quantity: '', unitValue: '', supplierName: '', invoiceNumber: '', contractId: '', commitment: '', lot: '', expiresAt: '', reason: '' }); const [message, setMessage] = useState('');
    const submit = async event => { event.preventDefault(); setMessage('Registrando...'); try { await AdministrativeCommandService.run('almoxarifado', 'recordMovement', form); setMessage('Movimentação registrada com sucesso.'); setTimeout(() => navigate('/admin/almoxarifado/movimentacoes'), 500); } catch (error) { setMessage(error.message); } };
    return <form className="data-card inventory-card inventory-form" onSubmit={submit}><div className="full"><h2>{defaultType === 'entry' ? 'Nova entrada' : 'Registrar movimentação'}</h2><p>O saldo será atualizado de forma transacional.</p></div><Field label="Tipo *"><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}>{Object.entries(MOVEMENT_TYPES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Produto *"><select required value={form.productId} onChange={e => setForm({ ...form, productId: e.target.value })}><option value="">Selecione</option>{products.map(item => <option key={item.id} value={item.id}>{item.code} — {item.description}</option>)}</select></Field><Field label="Depósito de origem *"><select required value={form.warehouseId} onChange={e => setForm({ ...form, warehouseId: e.target.value })}><option value="">Selecione</option>{warehouses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{form.type === 'transfer' && <Field label="Depósito de destino *"><select required value={form.destinationWarehouseId} onChange={e => setForm({ ...form, destinationWarehouseId: e.target.value })}><option value="">Selecione</option>{warehouses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}<Field label="Quantidade *"><input required type="number" min="0.001" step="0.001" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></Field><Field label="Valor unitário"><input type="number" min="0" step="0.01" value={form.unitValue} onChange={e => setForm({ ...form, unitValue: e.target.value })} /></Field><Field label="Fornecedor"><input value={form.supplierName} onChange={e => setForm({ ...form, supplierName: e.target.value })} /></Field><Field label="Nota fiscal"><input value={form.invoiceNumber} onChange={e => setForm({ ...form, invoiceNumber: e.target.value })} /></Field><Field label="Contrato relacionado"><input value={form.contractId} onChange={e => setForm({ ...form, contractId: e.target.value })} /></Field><Field label="Empenho"><input value={form.commitment} onChange={e => setForm({ ...form, commitment: e.target.value })} /></Field><Field label="Lote"><input value={form.lot} onChange={e => setForm({ ...form, lot: e.target.value })} /></Field><Field label="Validade"><input type="date" value={form.expiresAt} onChange={e => setForm({ ...form, expiresAt: e.target.value })} /></Field><Field label="Justificativa/observação" full><textarea rows="3" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></Field>{message && <p className="full inventory-feedback">{message}</p>}<div className="full inventory-actions"><button className="primary-button">Registrar movimentação</button></div></form>;
}

function Movements({ rows }) { return <section className="data-card inventory-card"><div className="inventory-heading"><div><h2>Movimentações</h2><p>Histórico imutável de alterações do estoque.</p></div></div><AdministrativeDataTable rows={rows} columns={[{ key: 'createdAt', label: 'Data', render: row => dateLabel(row.createdAt) }, { key: 'type', label: 'Tipo', render: row => MOVEMENT_TYPES[row.type] }, { key: 'productDescription', label: 'Produto' }, { key: 'quantity', label: 'Quantidade' }, { key: 'createdByName', label: 'Responsável' }, { key: 'invoiceNumber', label: 'Nota fiscal' }]} empty={<Empty title="Nenhuma movimentação" description="Entradas, saídas, transferências e ajustes aparecerão aqui." />} /></section>; }

function Requests({ rows, products, warehouses }) {
    const [form, setForm] = useState({ productId: '', warehouseId: '', quantity: 1, justification: '', departmentName: '' }); const [message, setMessage] = useState('');
    const submit = async event => { event.preventDefault(); const product = products.find(item => item.id === form.productId); try { await AdministrativeCommandService.run('almoxarifado', 'createRequest', { warehouseId: form.warehouseId, justification: form.justification, departmentName: form.departmentName, items: [{ productId: product.id, productDescription: product.description, quantity: form.quantity }] }); setForm({ productId: '', warehouseId: '', quantity: 1, justification: '', departmentName: '' }); setMessage('Requisição criada.'); } catch (error) { setMessage(error.message); } };
    const advance = async row => { const next = { requested: 'awaiting_authorization', awaiting_authorization: 'authorized', authorized: 'separating', separating: 'delivered', delivered: 'received' }[row.status]; if (!next) return; try { await AdministrativeCommandService.run('almoxarifado', 'transitionRequest', { id: row.id, status: next }); } catch (error) { setMessage(error.message); } };
    return <><PermissionGate permission="almoxarifado.solicitar"><form className="data-card inventory-card inventory-form" onSubmit={submit}><div className="full"><h2>Solicitar material</h2></div><Field label="Produto *"><select required value={form.productId} onChange={e => setForm({ ...form, productId: e.target.value })}><option value="">Selecione</option>{products.map(item => <option key={item.id} value={item.id}>{item.description} — disponível: {item.currentStock}</option>)}</select></Field><Field label="Depósito de atendimento *"><select required value={form.warehouseId} onChange={e => setForm({ ...form, warehouseId: e.target.value })}><option value="">Selecione</option>{warehouses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Quantidade *"><input required type="number" min="1" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></Field><Field label="Setor"><input value={form.departmentName} onChange={e => setForm({ ...form, departmentName: e.target.value })} /></Field><Field label="Justificativa *" full><textarea required rows="3" value={form.justification} onChange={e => setForm({ ...form, justification: e.target.value })} /></Field>{message && <p className="full inventory-feedback">{message}</p>}<div className="full inventory-actions"><button className="primary-button">Enviar requisição</button></div></form></PermissionGate><section className="data-card inventory-card"><h2>Requisições</h2><AdministrativeDataTable rows={rows} columns={[{ key: 'identifier', label: 'Número' }, { key: 'requesterName', label: 'Solicitante' }, { key: 'departmentName', label: 'Setor' }, { key: 'status', label: 'Situação', render: row => REQUEST_STATUS[row.status] || row.status }, { key: 'createdAt', label: 'Data', render: row => dateLabel(row.createdAt) }, { key: 'actions', label: 'Ações', render: row => <PermissionGate permission="almoxarifado.autorizar"><button className="inventory-small-button" disabled={!['requested', 'awaiting_authorization', 'authorized', 'separating', 'delivered'].includes(row.status)} onClick={() => advance(row)}>Avançar</button></PermissionGate> }]} empty={<Empty title="Nenhuma requisição" description="As solicitações de materiais aparecerão aqui." />} /></section></>;
}

export default function InventoryModulePage() {
    const location = useLocation(); const navigate = useNavigate();
    const products = useCollection('inventoryProducts'); const warehouses = useCollection('inventoryWarehouses'); const movements = useCollection('inventoryMovements'); const requests = useCollection('materialRequests');
    const page = location.pathname.split('/').filter(Boolean).pop(); const loading = products.loading || warehouses.loading || movements.loading || requests.loading; const error = products.error || warehouses.error || movements.error || requests.error;
    const content = useMemo(() => { if (page === 'produtos') return <Products rows={products.rows} />; if (page === 'depositos') return <Warehouses rows={warehouses.rows} />; if (page === 'entrada') return <MovementForm products={products.rows} warehouses={warehouses.rows} />; if (page === 'movimentacoes') return <Movements rows={movements.rows} />; if (page === 'requisicoes') return <Requests rows={requests.rows} products={products.rows} warehouses={warehouses.rows} />; return <Dashboard products={products.rows} movements={movements.rows} requests={requests.rows} />; }, [movements.rows, page, products.rows, requests.rows, warehouses.rows]);
    return <AdministrativeModuleLayout title="Almoxarifado" description="Controle materiais, depósitos, requisições e movimentações de estoque." navigation={NAVIGATION} actions={<PermissionGate permission="almoxarifado.movimentar"><button className="primary-button" onClick={() => navigate('/admin/almoxarifado/entrada')}><LiaPlusSolid /> Nova entrada</button></PermissionGate>}>{loading ? <div className="administrative-loading"><span />Carregando estoque...</div> : error ? <div className="administrative-error">Não foi possível carregar o almoxarifado. {error}</div> : content}</AdministrativeModuleLayout>;
}
