import React, { useEffect, useMemo, useState } from 'react';
import { collection, doc, getDoc, getDocs, onSnapshot, query, where } from 'firebase/firestore';
import { LiaBalanceScaleLeftSolid, LiaBuildingSolid, LiaCalendarAltSolid, LiaChartBarSolid, LiaFileAltSolid, LiaGavelSolid, LiaUserTieSolid, LiaUsersSolid } from 'react-icons/lia';
import { useAuth } from '../../contexts/FirebaseAuthContext';
import { useSystemControl } from '../../contexts/SystemControlContext';
import { isSystemRootEmail } from '../../config/systemModules';
import { LEGISLATIVE_COLLECTIONS } from '../../config/legislativeDataModel';
import { DEFAULT_LEGISLATIVE_CONFIGURATION, resolveLegislativeContext } from '../../services/LegislativeProcessService';
import { firestore } from '../../firebase';
import AdminSidebar from '../../components/AdminSidebar';
import CabinetLegislativeManagement from '../../components/CabinetLegislativeManagement';

export default function AdminLegislativo() {
  const { currentUser } = useAuth();
  const { settings } = useSystemControl();
  const [profile, setProfile] = useState({}); const [cabinets, setCabinets] = useState([]); const [commissions, setCommissions] = useState([]); const [rapporteurships, setRapporteurships] = useState([]); const [legislativeConfig, setLegislativeConfig] = useState({}); const [gabineteId, setGabineteId] = useState(''); const [access, setAccess] = useState('consulta'); const [loading, setLoading] = useState(true); const [section, setSection] = useState('minhas-materias');
  const isAdmin = ['Admin', 'Administrador'].includes(profile.tipo) || isSystemRootEmail(settings, currentUser?.email);
  const canChooseCabinet = isAdmin || ['Secretaria Legislativa', 'Juridico'].includes(profile.tipo) || Boolean(profile.presidenteCamara || profile.isCouncilPresident || (profile.legislativePermissions || []).includes('legislative.presidency'));
  useEffect(() => { if (!currentUser) return undefined; let active = true; getDoc(doc(firestore, 'users', currentUser.uid)).then(snapshot => { if (!active) return; const data = snapshot.data() || {}; setProfile(data); const role = String(data.tipo || ''); if (role === 'Vereador') { setGabineteId(data.gabineteId || data.vereadorId || currentUser.uid); setAccess('gestao'); } else if (role === 'Assessor') { getDocs(query(collection(firestore, 'gabinetes-equipe'), where('userId', '==', currentUser.uid))).then(result => { const membership = result.docs[0]?.data(); if (!active) return; setGabineteId(membership?.gabineteId || data.gabineteId || ''); setAccess(membership?.nivelAcesso || 'operacional'); }); } else { setAccess(['Secretaria Legislativa', 'Juridico'].includes(role) ? 'operacional' : 'consulta'); } }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [currentUser]);
  useEffect(() => { if (!canChooseCabinet) return undefined; return onSnapshot(query(collection(firestore, 'users'), where('tipo', '==', 'Vereador')), snapshot => setCabinets(snapshot.docs.map(row => ({ id: row.id, ...row.data() }))), () => setCabinets([])); }, [canChooseCabinet]);
  useEffect(() => { if (!gabineteId) { setCommissions([]); setRapporteurships([]); return undefined; } const camaraId = profile.camaraId || settings?.tenant?.id || settings?.tenant?.slug; const stopCommissions = camaraId ? onSnapshot(query(collection(firestore, LEGISLATIVE_COLLECTIONS.commissions), where('camaraId', '==', camaraId)), snapshot => setCommissions(snapshot.docs.map(row => ({ id: row.id, ...row.data() }))), () => setCommissions([])) : () => {}; const stopRapporteurships = onSnapshot(query(collection(firestore, LEGISLATIVE_COLLECTIONS.rapporteurships), where('gabineteId', '==', gabineteId)), snapshot => setRapporteurships(snapshot.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRapporteurships([])); return () => { stopCommissions(); stopRapporteurships(); }; }, [gabineteId, profile.camaraId, settings?.tenant?.id, settings?.tenant?.slug]);
  useEffect(() => { setLegislativeConfig({ ...DEFAULT_LEGISLATIVE_CONFIGURATION, ...(settings?.legislative || {}) }); }, [settings?.legislative]);
  const selectedGabinete = useMemo(() => cabinets.find(item => item.id === gabineteId), [cabinets, gabineteId]);
  const canOperate = access === 'gestao' || access === 'operacional';
  const isRoot = isSystemRootEmail(settings, currentUser?.email); const baseContext = resolveLegislativeContext({ userId: currentUser?.uid, profile, commissions, rapporteurships, legislativeConfig }); const actorContext = (isRoot || isAdmin) ? { ...baseContext, isCouncilPresident: true, permissions: [...new Set([...baseContext.permissions, 'legislative.secretariat', 'legislative.minutes', 'legislative.legalOpinion', 'legislative.presidency', 'legislative.rapporteur', 'legislative.commissionPresident'])] } : baseContext;
  const groups = [{ label: 'VISÃO GERAL', items: [['visao-geral', 'Dashboard', LiaBuildingSolid]] }, { label: 'TRAMITAÇÃO', items: [['minhas-materias', 'Minhas matérias', LiaBalanceScaleLeftSolid], ['pareceres', 'Pareceres', LiaGavelSolid], ['presidencia', 'Presidência', LiaUserTieSolid], ['arquivadas', 'Arquivadas', LiaFileAltSolid], ['comissoes', 'Comissões', LiaUsersSolid], ['sessoes', 'Sessões e pautas', LiaCalendarAltSolid]] }, { label: 'ADMINISTRAÇÃO', items: [['documentos', 'Documentos', LiaFileAltSolid], ['relatorios', 'Relatórios', LiaChartBarSolid]] }];
  return <div className="dashboard-layout"><AdminSidebar /><main className="dashboard-content cabinet-page-content legislative-page"><header className="page-header-container"><div><span className="escola-kicker">PODER LEGISLATIVO</span><h1>Gestão legislativa</h1><p>Matérias, tramitação, pautas, sessões, comissões e documentos acessórios.</p></div>{canChooseCabinet && <label className="cabinet-admin-selector">Gabinete de origem<select value={gabineteId} onChange={event => setGabineteId(event.target.value)}><option value="">Selecione o gabinete</option>{cabinets.map(item => <option key={item.id} value={item.id}>{item.vereadorNome || item.name || item.nome || item.email || 'Vereador(a)'}</option>)}</select></label>}</header><div className="legislative-workspace"><aside className="legislative-sidemenu" aria-label="Navegação da gestão legislativa"><div className="legislative-sidemenu-brand"><LiaBuildingSolid /><span>Legislativo</span></div>{groups.map(group => <section className="cabinet-nav-group" key={group.label}><span>{group.label}</span>{group.items.map(([id, label, Icon]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon /><em>{label}</em></button>)}</section>)}</aside><div className="legislative-view">{loading ? <section className="data-card"><p>Carregando permissões legislativas…</p></section> : !gabineteId ? <section className="data-card"><h2>Selecione um gabinete</h2><p>As matérias ficam relacionadas ao gabinete e ao vereador responsáveis.</p></section> : <CabinetLegislativeManagement gabineteId={gabineteId} vereadorId={selectedGabinete?.vereadorId || profile.vereadorId || gabineteId} camaraId={profile.camaraId || settings?.tenant?.id || settings?.tenant?.slug || ''} authorName={profile.name || profile.nome || currentUser?.displayName || currentUser?.email || 'Equipe legislativa'} canOperate={canOperate} canConfigure={isAdmin || isRoot} actorContext={actorContext} councilors={cabinets} section={section} />}</div></div></main></div>;
}
