import React, { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { LiaBookSolid, LiaFileAltSolid, LiaNewspaperSolid, LiaPlusSolid, LiaPlayCircleSolid, LiaTimesSolid } from 'react-icons/lia';
import AdminSidebar from '../../components/AdminSidebar';
import { firestore } from '../../firebase';
import { uploadFileToStorage } from '../../utils/firebaseStorageUtils';

const collections = { courses: 'escola-parlamento-cursos', lessons: 'escola-parlamento-aulas', contents: 'escola-parlamento-conteudos', news: 'escola-parlamento-noticias' };
const initial = { title: '', description: '', courseId: '', videoUrl: '', status: 'Publicado' };

const AdminEscolaParlamento = () => {
  const [active, setActive] = useState('courses'); const [courses, setCourses] = useState([]); const [items, setItems] = useState([]);
  const [form, setForm] = useState(initial); const [file, setFile] = useState(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true);
  const labels = { courses: 'Cursos', lessons: 'Aulas', contents: 'Conteúdos', news: 'Notícias' };
  const load = async () => { setLoading(true); try { const [courseSnap, itemSnap] = await Promise.all([getDocs(query(collection(firestore, collections.courses), orderBy('createdAt', 'desc'))), getDocs(query(collection(firestore, collections[active]), orderBy('createdAt', 'desc')))]); setCourses(courseSnap.docs.map(x => ({ id: x.id, ...x.data() }))); setItems(itemSnap.docs.map(x => ({ id: x.id, ...x.data() }))); } finally { setLoading(false); } };
  useEffect(() => { load().catch(error => console.error('Erro ao carregar Escola do Parlamento:', error)); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active]);
  const selectedCourseName = useMemo(() => new Map(courses.map(x => [x.id, x.title])), [courses]);
  const save = async event => { event.preventDefault(); try { let attachment = null; if (file) attachment = await uploadFileToStorage(file, 'escola-parlamento/conteudos'); const data = { ...form, title: form.title.trim(), createdAt: serverTimestamp(), updatedAt: serverTimestamp(), ...(attachment ? { attachment } : {}) }; if (active === 'courses') delete data.courseId; if (active !== 'lessons') delete data.videoUrl; await addDoc(collection(firestore, collections[active]), data); setOpen(false); setForm(initial); setFile(null); await load(); } catch (error) { console.error('Erro ao salvar Escola do Parlamento:', error); alert('Não foi possível salvar. Verifique a permissão e o arquivo selecionado.'); } };
  const remove = async id => { if (!window.confirm('Excluir este registro?')) return; await deleteDoc(doc(firestore, collections[active], id)); load(); };
  return (
    <div className="dashboard-layout"><AdminSidebar /><main className="dashboard-content escola-admin-page">
      <header className="page-header-container"><div className="header-title-section"><h1>Escola do Parlamento</h1><p>Gerencie cursos, aulas em vídeo, materiais e notícias.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><LiaPlusSolid /> Novo</button></header>
      <nav className="service-operations-nav escola-tabs">{Object.entries(labels).map(([id, label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}>{id === 'courses' ? <LiaBookSolid /> : id === 'lessons' ? <LiaPlayCircleSolid /> : id === 'contents' ? <LiaFileAltSolid /> : <LiaNewspaperSolid />}{label}</button>)}</nav>
      <section className="data-card"><div className="card-header"><div><h2>{labels[active]}</h2><p>Gerencie os registros publicados da Escola.</p></div></div>{loading ? <p>Carregando...</p> : <div className="escola-admin-list">{items.length === 0 && <p>Nenhum registro cadastrado.</p>}{items.map(item => <article key={item.id}><div><strong>{item.title}</strong><span>{item.courseId ? selectedCourseName.get(item.courseId) || 'Curso não informado' : item.status || 'Publicado'}</span>{item.videoUrl && <a href={item.videoUrl} target="_blank" rel="noreferrer">Abrir vídeo</a>}{item.attachment?.url && <a href={item.attachment.url} target="_blank" rel="noreferrer">Abrir material: {item.attachment.name}</a>}</div><button className="btn-secondary" onClick={() => remove(item.id)}>Excluir</button></article>)}</div>}</section>
      {open && <div className="modal-overlay" onClick={() => setOpen(false)}><form className="modal-content escola-modal" onSubmit={save} onClick={e => e.stopPropagation()}><div className="modal-header"><h2>Novo registro</h2><button type="button" className="modal-close-btn" onClick={() => setOpen(false)}><LiaTimesSolid /></button></div><div className="modal-body"><label className="form-group"><span>Título</span><input required className="form-input" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label>{active !== 'courses' && <label className="form-group"><span>Curso</span><select className="form-input" required={active !== 'news'} value={form.courseId} onChange={e => setForm({ ...form, courseId: e.target.value })}><option value="">{active === 'news' ? 'Notícia geral da Escola' : 'Selecione um curso'}</option>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label>}<label className="form-group"><span>{active === 'news' ? 'Resumo' : 'Descrição'}</span><textarea className="form-input" rows="5" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label>{active === 'lessons' && <label className="form-group"><span>Link do vídeo</span><input required type="url" className="form-input" placeholder="YouTube, Vimeo ou outro endereço de vídeo" value={form.videoUrl} onChange={e => setForm({ ...form, videoUrl: e.target.value })} /></label>}{active === 'contents' && <label className="form-group"><span>PDF ou imagem</span><input required type="file" accept="application/pdf,image/*" onChange={e => setFile(e.target.files?.[0] || null)} /></label>}<label className="form-group"><span>Status</span><select className="form-input" value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>Publicado</option><option>Rascunho</option></select></label></div><div className="form-actions"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="btn-primary">Salvar</button></div></form></div>}
    </main></div>
  );
};
export default AdminEscolaParlamento;
