import React, {useCallback, useEffect, useState} from 'react';
import {Link, Navigate} from 'react-router-dom';
import {httpsCallable} from 'firebase/functions';
import {functions} from '../../firebase';
import {useAuth} from '../../contexts/FirebaseAuthContext';
import {useSystemControl} from '../../contexts/SystemControlContext';
import Sidebar from '../../components/Sidebar';
import AdminSidebar from '../../components/AdminSidebar';
import CabinetOverlay from '../../components/CabinetOverlay';
import './esic.css';
const api = async data => (await httpsCallable(functions, 'esic')(data)).data;
const date = value => value ? new Date(value).toLocaleString('pt-BR') : '—';
const statuses = ['Recebido','Em análise','Respondido','Em recurso','Concluído'];
const configLabels = {responsavel:'Responsável pelo SIC',email:'E-mail de atendimento',telefone:'Telefone',endereco:'Endereço do atendimento presencial',horario:'Horário de atendimento',regulamento:'Link da regulamentação local',autoridadeRecursal:'E-mail do usuário responsável pelos recursos'};

export function EsicPublico() {
  const {settings} = useSystemControl();
  const [config,setConfig] = useState({});
  useEffect(() => { api({action:'public'}).then(setConfig).catch(() => {}); },[]);
  return <main className="ouvidoria-public-shell esic-page"><header className="ouvidoria-public-header"><Link to="/">{settings.tenant.name}</Link><nav><Link to="/ouvidoria-publica">Ouvidoria</Link><Link to="/esic">Acessar meus pedidos</Link></nav></header>
    <section className="esic-panel"><span>TRANSPARÊNCIA E ACESSO À INFORMAÇÃO</span><h1>Serviço de Informação ao Cidadão</h1><p>Solicite documentos e informações públicas da Câmara, acompanhe a resposta e apresente recurso. Não é necessário explicar por que você precisa da informação.</p><div className="esic-actions"><Link className="btn-primary" to="/esic">Solicitar informação</Link><Link className="btn-secondary" to="/esic">Acompanhar pedido</Link></div></section>
    <div className="esic-grid"><article className="esic-panel"><h2>Como funciona</h2><ol><li>Entre com sua conta do Portal.</li><li>Descreva a informação desejada de forma clara.</li><li>Guarde o protocolo e acompanhe seu pedido.</li><li>Consulte a resposta e, se necessário, apresente recurso.</li></ol><p>Pedidos de informação são identificados. Para denúncias e reclamações, inclusive anônimas, utilize a <Link to="/ouvidoria-publica">Ouvidoria</Link>.</p></article>
    <article className="esic-panel"><h2>Prazos e direitos</h2><p>Informações disponíveis devem ser fornecidas imediatamente. Quando isso não for possível, o prazo legal é de até 20 dias, prorrogável por mais 10 dias com justificativa.</p><p>Em caso de negativa, cabe recurso em até 10 dias da ciência, dirigido à autoridade superior, com decisão em até 5 dias. A regulamentação local define as instâncias competentes.</p><a href="https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm" target="_blank" rel="noreferrer">Consultar a Lei de Acesso à Informação</a></article></div>
    <section className="esic-panel"><h2>Atendimento presencial e contatos</h2>{['responsavel','email','telefone','endereco','horario'].map(key => <p key={key}><strong>{configLabels[key]}: </strong>{config[key] || (key==='endereco' ? settings.tenant.address : '') || 'Informação ainda não cadastrada pela Câmara.'}</p>)}{config.regulamento?.startsWith('https://') && <a href={config.regulamento} target="_blank" rel="noreferrer">Regulamentação local da LAI</a>}</section>
    <section className="esic-panel"><h2>Perguntas frequentes</h2><details><summary>Quem pode solicitar?</summary><p>Qualquer pessoa física ou jurídica pode solicitar informações públicas.</p></details><details><summary>O serviço tem custo?</summary><p>A busca e o fornecimento são gratuitos. Eventuais custos de reprodução seguem a LAI e devem ser informados previamente.</p></details><details><summary>Quais informações devo enviar?</summary><p>Identificação e descrição suficiente para localizar a informação. Evite incluir dados pessoais desnecessários no texto.</p></details></section>
  </main>;
}

export default function Esic({admin=false}) {
  const {currentUser,loading,role} = useAuth();
  const [stats,setStats]=useState({});
  const [items,setItems] = useState([]), [cursor,setCursor] = useState(null), [busy,setBusy] = useState(false), [error,setError] = useState('');
  const [status,setStatus] = useState(''), [search,setSearch] = useState(''), [detail,setDetail] = useState(null), [modal,setModal] = useState(''), [notice,setNotice] = useState('');
  const load = useCallback(async (next=null) => { setBusy(true);setError('');try { const result=await api({action:'list',admin,status,protocolo:search,cursor:next});setItems(old=>next?[...old,...result.items]:result.items);setCursor(result.cursor); if(admin)setStats(await api({action:'stats'})); } catch(e){setError(e.message);}finally{setBusy(false);} },[admin,status,search]);
  useEffect(()=> { if(currentUser) { if(admin)api({action:'stats'}).then(setStats).catch(()=>{}); setBusy(true); api({action:'list',admin}).then(r=>{setItems(r.items);setCursor(r.cursor);}).catch(e=>setError(e.message)).finally(()=>setBusy(false)); } },[currentUser,admin]);
  async function open(id) {setBusy(true);setError('');try {let result=await api({action:'detail',id}); if(result.userId===currentUser.uid && result.status==='Respondido' && !result.cienciaAt){await api({action:'acknowledge',id});result=await api({action:'detail',id});} setDetail(result);setModal('detail');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function submit(event) {event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try {const result=await api({...values,action:modal==='new'?'create':modal,id:detail?.id});setNotice(result.protocolo ? `Pedido recebido. Protocolo: ${result.protocolo}`:'Registro salvo.'); if(detail && modal!=='config'){setDetail(await api({action:'detail',id:detail.id}));setModal('detail');}else setModal('');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function upload(event) {const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){setError('O limite é de 5 MB.');return;}setBusy(true);setError('');try {const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await api({action:'upload',id:detail.id,name:file.name,base64});setDetail(await api({action:'detail',id:detail.id}));}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function download(fileId) {setBusy(true);setError('');try {const result=await api({action:'download',id:detail.id,fileId});const bytes=Uint8Array.from(atob(result.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:result.mime}));const a=document.createElement('a');a.href=url;a.download=result.name;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}finally{setBusy(false);}}
  function csv(){const rows=[['Protocolo','Assunto','Status','Prazo','Responsável'],...items.map(i=>[i.protocolo,i.titulo,i.status,date(i.deadline),i.responsavel])];const safe=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='pedidos-esic.csv';a.click();URL.revokeObjectURL(url);}
  if(loading) return <p>Carregando…</p>;
  if(!currentUser) return <Navigate to="/login" replace state={{returnTo:admin?'/admin-esic':'/esic'}}/>;
  return <div className="dashboard-layout">{admin?<AdminSidebar/>:<Sidebar/>}<main className="dashboard-content esic-page"><div className="esic-boundary"><header className="page-header-container"><div><h1>{admin?'Central e-SIC':'Meus pedidos de informação'}</h1><p>{admin?'Organize a análise, acompanhe prazos e responda ao cidadão.':'Acompanhe seus protocolos e as respostas da Câmara.'}</p></div></header>
    <section className="esic-panel">{admin&&<div className="esic-stats">{Object.entries(stats).map(([label,total])=><article key={label}><span>{label}</span><strong>{total}</strong></article>)}</div>}<div className="esic-actions">{!admin&&<button onClick={()=>{setDetail(null);setModal('new');}}>Novo pedido</button>}{admin&&<><button onClick={csv}>Exportar registros carregados (CSV)</button>{role==='Admin'&&<button onClick={()=>setModal('config')}>Configurar atendimento</button>}</>}</div><form className="esic-filters" onSubmit={e=>{e.preventDefault();load();}}><label>Protocolo<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="SIC-2026-000001"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy}>Buscar</button></form>
    {notice&&<p role="status">{notice}</p>}{error&&!modal&&<p role="alert">{error}</p>}{busy&&<p role="status">Carregando…</p>}
    {!items.length&&!busy&&<p>Nenhum pedido encontrado. {admin?'Ajuste os filtros para pesquisar.':'Registre seu primeiro pedido de informação.'}</p>}
    <div className="esic-list">{items.map(item=><button key={item.id} className="esic-record" onClick={()=>open(item.id)}><span><strong>{item.protocolo}</strong><span>{item.titulo}</span></span><span>{item.status}<small>{!['Respondido','Concluído'].includes(item.status)&&item.deadline<Date.now()?'Prazo vencido · ':''}{date(item.deadline)}</small></span></button>)}</div>{cursor&&<button disabled={busy} onClick={()=>load(cursor)}>Carregar mais 25</button>}</section></div></main>
    {modal&&<CabinetOverlay onClick={()=>!busy&&setModal('')}><section className="modal-content esic-dialog" onClick={e=>e.stopPropagation()}><header className="modal-header"><h2>{({new:'Novo pedido de informação',detail:detail?.protocolo,assign:'Distribuir pedido',extend:'Prorrogar prazo',respond:'Responder pedido',appeal:'Apresentar recurso',decide:'Decidir recurso',note:'Observação interna',config:'Configuração do SIC'})[modal]}</h2><button type="button" disabled={busy} onClick={()=>setModal('')} aria-label="Fechar">×</button></header>{error&&<p role="alert">{error}</p>}
    {modal==='detail'?<><p><strong>{detail.titulo}</strong></p><p className="esic-text">{detail.descricao}</p><p>Status: {detail.status} · Prazo: {date(detail.deadline)}</p><p>Responsável: {detail.responsavel||'Aguardando distribuição'} · Setor: {detail.setor||'SIC'}</p><div className="esic-actions">{admin&&<>{['Recebido','Em análise'].includes(detail.status)&&<><button onClick={()=>setModal('assign')}>Distribuir</button><button onClick={()=>setModal('respond')}>Responder</button>{!detail.prorrogado&&<button onClick={()=>setModal('extend')}>Prorrogar</button>}</>}{detail.status==='Em recurso'&&<button onClick={()=>setModal('decide')}>Decidir recurso</button>}<button onClick={()=>setModal('note')}>Nota interna</button></>}{detail.userId===currentUser.uid&&detail.status==='Respondido'&&<button onClick={()=>setModal('appeal')}>Apresentar recurso</button>}</div><h3>Anexos</h3><p>PDF, JPG ou PNG, até 5 MB por arquivo.</p>{(admin||['Recebido','Em análise'].includes(detail.status))&&<label>Adicionar anexo<input type="file" accept=".pdf,.jpg,.jpeg,.png" disabled={busy} onChange={upload}/></label>}<div className="esic-actions">{detail.anexos?.map(file=><button disabled={busy} key={file.id} onClick={()=>download(file.id)}>{file.name}</button>)}</div><h3>Histórico</h3><ol className="esic-timeline">{detail.historico.map(h=><li key={h.id}><strong>{h.acao}{h.interno?' · Interno':''}</strong><small>{date(h.data)}</small><p className="esic-text">{h.texto}</p></li>)}</ol></>:<form onSubmit={submit}>
    {modal==='new'?<><p>Descreva a informação desejada. Não é preciso justificar o motivo do pedido.</p><label>Assunto<input name="titulo" maxLength={200} required/></label><label>Descrição<textarea name="descricao" minLength={20} maxLength={20000} required/></label></>:modal==='config'?<EsicConfig/>:<>{modal==='assign'&&<><label>Responsável<input name="responsavel" required/></label><label>Setor<input name="setor" required/></label></>}{modal==='respond'&&<label>Resultado<select name="resultado" required>{['Acesso concedido','Acesso parcial','Acesso negado','Informação inexistente','Órgão não competente'].map(v=><option key={v}>{v}</option>)}</select></label>}<label>{modal==='note'?'Nota visível somente à equipe':'Resposta ou justificativa (visível ao solicitante)'}<textarea name="texto" required minLength={modal==='appeal'?20:1} maxLength={20000}/></label></>}
    <button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></form>}</section></CabinetOverlay>}
  </div>;
}
function EsicConfig(){const [config,setConfig]=useState(null);useEffect(()=>{api({action:'public'}).then(setConfig);},[]);if(!config)return <p>Carregando configuração…</p>;return Object.entries(configLabels).map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={config[key]||''} type={key==='email'||key==='autoridadeRecursal'?'email':key==='regulamento'?'url':'text'}/></label>);}
