import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { addDoc, collection, getDocs, query, serverTimestamp, where } from 'firebase/firestore';
import { LiaBookSolid, LiaNewspaperSolid, LiaPlayCircleSolid, LiaTimesSolid } from 'react-icons/lia';
import Sidebar from '../../components/Sidebar';
import { auth, firestore } from '../../firebase';

const fetchPublished = async name => (await getDocs(collection(firestore, name))).docs.map(item => ({ id: item.id, ...item.data() })).filter(item => item.status === 'Publicado');
const videoEmbedUrl = url => { const youtube = (url || '').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([^?&/]+)/); if (youtube) return `https://www.youtube.com/embed/${youtube[1]}`; const vimeo = (url || '').match(/vimeo\.com\/(?:video\/)?(\d+)/); return vimeo ? `https://player.vimeo.com/video/${vimeo[1]}` : url; };
const videoThumbnail = url => { const youtube = (url || '').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([^?&/]+)/); return youtube ? `https://i.ytimg.com/vi/${youtube[1]}/hqdefault.jpg` : ''; };
const sanitizeRichContent = html => (html || '').replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi, '').replace(/\son\w+\s*=\s*(['"]).*?\1/gi, '');

const EscolaParlamento = () => {
  const [courses, setCourses] = useState([]); const [news, setNews] = useState([]); const [enrolled, setEnrolled] = useState([]); const [newsSlide, setNewsSlide] = useState(0); const [courseSlide, setCourseSlide] = useState(0); const [selectedCourse, setSelectedCourse] = useState(null);
  useEffect(() => { Promise.all([fetchPublished('escola-parlamento-cursos'), fetchPublished('escola-parlamento-noticias')]).then(([courseData, newsData]) => { setCourses(courseData); setNews(newsData); }).catch(error => console.error('Erro ao carregar Escola do Parlamento:', error)); }, []);
  useEffect(() => { const user = auth.currentUser; if (!user) return setEnrolled([]); getDocs(query(collection(firestore, 'escola-parlamento-matriculas'), where('userId', '==', user.uid))).then(snapshot => setEnrolled(snapshot.docs.map(item => item.data().courseId))).catch(error => console.error('Erro ao carregar matrículas:', error)); }, []);
  const enroll = async course => { const user = auth.currentUser; if (!user) return alert('Entre em sua conta para se matricular neste curso.'); if (!enrolled.includes(course.id)) { await addDoc(collection(firestore, 'escola-parlamento-matriculas'), { courseId: course.id, userId: user.uid, userName: user.displayName || '', userEmail: user.email || '', createdAt: serverTimestamp() }); setEnrolled([...enrolled, course.id]); } setSelectedCourse(null); window.location.assign('/escola-parlamento/meus-cursos'); };
  const visibleCourses = courses.length > 3 ? [0, 1, 2].map(offset => courses[(courseSlide + offset) % courses.length]) : courses;
  return <div className="dashboard-layout"><Sidebar onItemClick={path => window.location.assign(path)} /><main className="dashboard-content escola-public-page">
    <header className="page-header-container"><div className="header-title-section"><span className="escola-kicker">Formação cidadã e legislativa</span><h1>Escola do Parlamento</h1><p>Cursos, aulas e materiais para aproximar a Câmara da população.</p></div><button className="btn-secondary escola-my-courses-button" onClick={() => window.location.assign('/escola-parlamento/meus-cursos')}><LiaBookSolid /> Meus cursos</button></header>
    <section className="escola-news escola-news-slider"><div className="card-header"><h2><LiaNewspaperSolid /> Notícias da Escola</h2></div>{news.length ? <>{news[newsSlide % news.length].coverUrl && <img className="escola-news-slide-cover" src={news[newsSlide % news.length].coverUrl} alt="" />}<article><strong>{news[newsSlide % news.length].title}</strong><p>{news[newsSlide % news.length].summary || news[newsSlide % news.length].description}</p>{news[newsSlide % news.length].content && <div className="escola-news-rich-content" dangerouslySetInnerHTML={{ __html: sanitizeRichContent(news[newsSlide % news.length].content) }} />}</article>{news.length > 1 && <div className="escola-slider-controls"><button onClick={() => setNewsSlide((newsSlide - 1 + news.length) % news.length)}>Anterior</button><span>{(newsSlide % news.length) + 1} de {news.length}</span><button onClick={() => setNewsSlide((newsSlide + 1) % news.length)}>Próxima</button></div>}</> : <p>Em breve, novidades da Escola do Parlamento.</p>}</section>
    <section className="escola-course-showcase"><div className="escola-showcase-heading"><div><span className="escola-kicker">Cursos disponíveis</span><h2>Aprenda no seu ritmo</h2><p>Escolha um curso para conhecer a proposta e se matricular.</p></div>{courses.length > 3 && <div className="escola-slider-controls"><button onClick={() => setCourseSlide((courseSlide - 1 + courses.length) % courses.length)}>Anterior</button><button onClick={() => setCourseSlide((courseSlide + 1) % courses.length)}>Próximo</button></div>}</div><div className="escola-course-slider">{visibleCourses.map(course => <article key={course.id} className="escola-course-slide" onClick={() => setSelectedCourse(course)} role="button" tabIndex={0} onKeyDown={event => event.key === 'Enter' && setSelectedCourse(course)}>{videoThumbnail(course.presentationVideoUrl) ? <img src={videoThumbnail(course.presentationVideoUrl)} alt="" /> : <div className="escola-course-placeholder"><LiaPlayCircleSolid /></div>}<div><h3>{course.title}</h3><p>{course.description || 'Curso da Escola do Parlamento.'}</p></div><footer><button className="btn-secondary" onClick={event => { event.stopPropagation(); setSelectedCourse(course); }}>Ver apresentação</button><button className="btn-primary" onClick={event => { event.stopPropagation(); enroll(course); }}>{enrolled.includes(course.id) ? 'Acessar meus cursos' : 'Matricular-se'}</button></footer></article>)}</div>{!courses.length && <p>Nenhum curso publicado.</p>}</section>
    {selectedCourse && createPortal(<div className="modal-overlay escola-global-overlay" onClick={() => setSelectedCourse(null)}><section className="modal-content escola-course-preview-modal" onClick={event => event.stopPropagation()}><div className="modal-header"><div><span className="escola-kicker">Apresentação do curso</span><h2>{selectedCourse.title}</h2></div><button type="button" className="modal-close-btn" aria-label="Fechar" onClick={() => setSelectedCourse(null)}><LiaTimesSolid /></button></div>{selectedCourse.presentationVideoUrl && <div className="escola-video-player"><iframe src={videoEmbedUrl(selectedCourse.presentationVideoUrl)} title={`Apresentação: ${selectedCourse.title}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>}<div className="escola-course-preview-description"><p>{selectedCourse.description || 'Conheça o conteúdo e participe desta formação.'}</p><button className="btn-primary" onClick={() => enroll(selectedCourse)}>{enrolled.includes(selectedCourse.id) ? 'Acessar meus cursos' : 'Matricular-se neste curso'}</button></div></section></div>, document.body)}
  </main></div>;
};
export default EscolaParlamento;
