import React, { useEffect, useMemo, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { LiaBookSolid, LiaFileAltSolid, LiaNewspaperSolid, LiaPlayCircleSolid } from 'react-icons/lia';
import Sidebar from '../../components/Sidebar';
import { firestore } from '../../firebase';

const fetchPublic = async name => (await getDocs(collection(firestore, name))).docs.map(x => ({ id: x.id, ...x.data() })).filter(item => item.status === 'Publicado');
const EscolaParlamento = () => {
 const [courses, setCourses] = useState([]); const [lessons, setLessons] = useState([]); const [contents, setContents] = useState([]); const [news, setNews] = useState([]); const [activeCourse, setActiveCourse] = useState('');
 useEffect(() => { Promise.all([fetchPublic('escola-parlamento-cursos'), fetchPublic('escola-parlamento-aulas'), fetchPublic('escola-parlamento-conteudos'), fetchPublic('escola-parlamento-noticias')]).then(([a,b,c,d]) => { setCourses(a); setLessons(b); setContents(c); setNews(d); }).catch(error => console.error('Erro ao carregar Escola do Parlamento:', error)); }, []);
 const selected = activeCourse || courses[0]?.id || ''; const course = useMemo(() => courses.find(x => x.id === selected), [courses, selected]);
 return <div className="dashboard-layout"><Sidebar onItemClick={path => window.location.assign(path)} /><main className="dashboard-content escola-public-page"><header className="page-header-container"><div className="header-title-section"><span className="escola-kicker">Formação cidadã e legislativa</span><h1>Escola do Parlamento</h1><p>Cursos, aulas e materiais para aproximar a Câmara da população.</p></div></header><section className="escola-news"><div className="card-header"><h2><LiaNewspaperSolid /> Notícias da Escola</h2></div>{news.length ? news.map(item => <article key={item.id}><strong>{item.title}</strong><p>{item.description}</p></article>) : <p>Em breve, novidades da Escola do Parlamento.</p>}</section><section className="escola-course-layout"><aside><h2><LiaBookSolid /> Cursos</h2>{courses.length ? courses.map(item => <button key={item.id} className={selected === item.id ? 'active' : ''} onClick={() => setActiveCourse(item.id)}><strong>{item.title}</strong><span>{item.description}</span></button>) : <p>Nenhum curso publicado.</p>}</aside><section className="data-card"><h2>{course?.title || 'Escolha um curso'}</h2><p>{course?.description}</p><h3><LiaPlayCircleSolid /> Aulas</h3>{lessons.filter(item => item.courseId === selected).map(item => <article className="escola-resource" key={item.id}><div><strong>{item.title}</strong><span>{item.description}</span></div><a className="btn-primary" href={item.videoUrl} target="_blank" rel="noreferrer">Assistir</a></article>)}<h3><LiaFileAltSolid /> Materiais</h3>{contents.filter(item => item.courseId === selected).map(item => <article className="escola-resource" key={item.id}><div><strong>{item.title}</strong><span>{item.description}</span></div><a className="btn-secondary" href={item.attachment?.url} target="_blank" rel="noreferrer">Abrir material</a></article>)}</section></section></main></div>;
};
export default EscolaParlamento;
