import React, { useEffect, useState } from 'react';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { LiaBookSolid, LiaPlayCircleSolid } from 'react-icons/lia';
import Sidebar from '../../components/Sidebar';
import { auth, firestore } from '../../firebase';

const MeusCursosEscola = () => {
  const [courses, setCourses] = useState([]); const [enrollments, setEnrollments] = useState([]); const [progress, setProgress] = useState([]);
  useEffect(() => { const user = auth.currentUser; if (!user) return; Promise.all([getDocs(collection(firestore, 'escola-parlamento-cursos')), getDocs(query(collection(firestore, 'escola-parlamento-matriculas'), where('userId', '==', user.uid))), getDocs(query(collection(firestore, 'escola-parlamento-progresso'), where('userId', '==', user.uid))), getDocs(collection(firestore, 'escola-parlamento-aulas'))]).then(([courseData, enrollmentData, progressData, lessonData]) => { const lessonCount = lessonData.docs.filter(item => item.data().status === 'Publicado').reduce((map, item) => ({ ...map, [item.data().courseId]: (map[item.data().courseId] || 0) + 1 }), {}); setCourses(courseData.docs.map(item => ({ id: item.id, ...item.data(), lessonCount: lessonCount[item.id] || 0 }))); setEnrollments(enrollmentData.docs.map(item => item.data())); setProgress(progressData.docs.map(item => item.data())); }); }, []);
  return <div className="dashboard-layout"><Sidebar onItemClick={path => window.location.assign(path)} /><main className="dashboard-content escola-public-page"><header className="page-header-container"><div className="header-title-section"><span className="escola-kicker">Minha aprendizagem</span><h1>Meus cursos</h1><p>Acompanhe suas aulas assistidas e continue de onde parou.</p></div></header><section className="escola-my-courses">{enrollments.length ? enrollments.map(enrollment => { const course = courses.find(item => item.id === enrollment.courseId); const watched = new Set(progress.filter(item => item.courseId === enrollment.courseId).map(item => item.lessonId).filter(Boolean)).size; const total = course?.lessonCount || 0; const percentage = total ? Math.min(100, Math.round((watched / total) * 100)) : 0; return <article key={enrollment.courseId}><LiaBookSolid /><div><h2>{course?.title || 'Curso'}</h2><p>{watched} de {total} aulas assistidas</p><div className="escola-progress"><i style={{ width: `${percentage}%` }} /></div><strong>{percentage}% concluído</strong></div><button className="btn-primary" onClick={() => window.location.assign(`/escola-parlamento/curso/${enrollment.courseId}`)}>Continuar <LiaPlayCircleSolid /></button></article>; }) : <p>Você ainda não está matriculado em nenhum curso.</p>}</section></main></div>;
};
export default MeusCursosEscola;
