import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { addDoc, collection, doc, getDoc, onSnapshot, query, serverTimestamp, setDoc, where } from 'firebase/firestore';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { LiaBullhornSolid, LiaCalendarSolid, LiaCommentsSolid, LiaIdCardSolid } from 'react-icons/lia';
import Sidebar from '../../components/Sidebar';
import VereadorAppointmentOffer from '../../components/VereadorAppointmentOffer';
import { useAuth } from '../../contexts/FirebaseAuthContext';
import { firestore, storage } from '../../firebase';
import { DEMAND_STATUSES, statusLabel } from '../../config/cabinetMandate';

const TABS = ['Visão geral', 'Solicitar reunião', 'Enviar demanda', 'Visitante', 'Mensagens'];
const emptyRequest = { vereadorId:'', vereadorNome:'', assunto:'', descricao:'', alcance:'Individual', categoria:'Outra demanda' };
const compressWebp = file => new Promise((resolve, reject) => { const image=new Image(), url=URL.createObjectURL(file); image.onload=()=>{const scale=Math.min(1,1280/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error('Não foi possível processar a imagem.'))},'image/webp',.72)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Imagem inválida.'))};image.src=url; });

export default function SolicitacoesVereadores() {
  const navigate=useNavigate(), {currentUser}=useAuth();
  const [tab,setTab]=useState(TABS[0]), [items,setItems]=useState([]), [members,setMembers]=useState([]), [messages,setMessages]=useState([]), [registrations,setRegistrations]=useState([]), [profile,setProfile]=useState({});
  const [form,setForm]=useState(emptyRequest), [visitor,setVisitor]=useState({vereadorId:''}), [text,setText]=useState(''), [files,setFiles]=useState([]), [selfie,setSelfie]=useState(null), [saving,setSaving]=useState(false), [feedback,setFeedback]=useState('');
  useEffect(()=>{if(!currentUser){navigate('/login');return undefined}getDoc(doc(firestore,'users',currentUser.uid)).then(s=>setProfile(s.data()||{}));const stops=[onSnapshot(collection(firestore,'vereadores'),s=>setMembers(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(query(collection(firestore,'solicitacoes-vereadores'),where('userId','==',currentUser.uid)),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()})))),onSnapshot(query(collection(firestore,'gabinetes-mensagens'),where('userId','==',currentUser.uid)),s=>setMessages(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.criadoEm?.toMillis?.()||0)-(b.criadoEm?.toMillis?.()||0)))),onSnapshot(query(collection(firestore,'gabinetes-visitantes'),where('userId','==',currentUser.uid)),s=>setRegistrations(s.docs.map(d=>({id:d.id,...d.data()}))))];return()=>stops.forEach(stop=>stop())},[currentUser,navigate]);
  const selected=id=>{const v=members.find(item=>(item.userId||item.id)===id);return {vereadorId:id,vereadorNome:v?.name||v?.nome||'Vereador(a)'}};
  const upload=async(source,prefix,cabinetId)=>Promise.all([...source].map(async(file,index)=>{const image=file.type.startsWith('image/'),blob=image?await compressWebp(file):file,extension=image?'webp':(file.name.split('.').pop()||'bin'),target=ref(storage,`gabinetes/${cabinetId}/${currentUser.uid}/${prefix}-${Date.now()}-${index}.${extension}`);await uploadBytes(target,blob,{contentType:image?'image/webp':file.type});return getDownloadURL(target)}));
  const userData=()=>({id:currentUser.uid,email:profile.email||currentUser.email,name:profile.name||currentUser.displayName||'Cidadão',phone:profile.phone||'',address:profile.address||'',birthDate:profile.birthDate||profile.dataNascimento||''});
  const submitRequest=async(event,isMeeting)=>{event.preventDefault();if(isMeeting&&!registrations.some(item=>item.gabineteId===form.vereadorId)){setFeedback('Finalize seu cadastro de visitante neste gabinete antes de solicitar uma reunião.');return}setSaving(true);setFeedback('');try{const photos=files.length?await upload(files,'demanda',form.vereadorId):[],protocol=`GAB-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;await addDoc(collection(firestore,'solicitacoes-vereadores'),{protocolo:protocol,userId:currentUser.uid,gabineteId:form.vereadorId,tipoDemanda:isMeeting?'Atendimento no gabinete':form.categoria,dadosUsuario:userData(),dadosSolicitacao:{...form,categoriaDemanda:isMeeting?'Atendimento no gabinete':form.categoria,tipoAtendimento:'Presencial'},fotos:photos,status:isMeeting?'Aguardando Análise':'RECEBIDA',prioridade:'Normal',dataSolicitacao:serverTimestamp()});setForm(emptyRequest);setFiles([]);setFeedback(`${isMeeting?'Pedido de reunião':'Solicitação'} recebida pelo gabinete. Protocolo ${protocol}.`);setTab(TABS[0])}catch(error){setFeedback(error.message)}finally{setSaving(false)}};
  const registerVisitor=async event=>{event.preventDefault();if(!selfie){setFeedback('A selfie é obrigatória.');return}setSaving(true);try{const [selfieUrl]=await upload([selfie],'selfie',visitor.vereadorId);await setDoc(doc(firestore,'gabinetes-visitantes',`${visitor.vereadorId}_${currentUser.uid}`),{...userData(),userId:currentUser.uid,selfieUrl,gabineteId:visitor.vereadorId,criadoEm:serverTimestamp(),cadastroCompleto:true});setFeedback('Cadastro finalizado. Você já pode solicitar uma reunião neste gabinete.');setSelfie(null);setTab(TABS[1]);setForm({...form,...selected(visitor.vereadorId)})}catch(error){setFeedback(error.message)}finally{setSaving(false)}};
  const sendMessage=async event=>{event.preventDefault();if(!form.vereadorId||!text.trim())return;await addDoc(collection(firestore,'gabinetes-mensagens'),{gabineteId:form.vereadorId,userId:currentUser.uid,nomeUsuario:profile.name||currentUser.email,texto:text.trim(),autorId:currentUser.uid,autorTipo:'cidadao',criadoEm:serverTimestamp()});setText('')};
  const cards=useMemo(()=>[...items].sort((a,b)=>(b.dataSolicitacao?.toMillis?.()||0)-(a.dataSolicitacao?.toMillis?.()||0)),[items]);
  const memberSelect=(value,onChange)=><select required value={value} onChange={event=>onChange(event.target.value)}><option value="">Selecione o vereador</option>{members.map(v=><option key={v.id} value={v.userId||''} disabled={!v.userId}>{v.name||v.nome}{!v.userId?' — indisponível para atendimento':''}</option>)}</select>;
  const requestForm=isMeeting=><section className="data-card council-form-card"><h2>{isMeeting?'Solicitar reunião':'Enviar demanda ou denúncia'}</h2><form onSubmit={event=>submitRequest(event,isMeeting)}>{memberSelect(form.vereadorId,id=>setForm({...form,...selected(id)}))}{isMeeting?<select value={form.alcance} onChange={e=>setForm({...form,alcance:e.target.value})}><option>Individual</option><option>Comunitária</option></select>:<select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}><option>Poda de árvores</option><option>Tapa-buracos</option><option>Iluminação pública</option><option>Limpeza urbana</option><option>Denúncia</option><option>Outra demanda</option></select>}<input required placeholder="Assunto" value={form.assunto} onChange={e=>setForm({...form,assunto:e.target.value})}/><textarea required minLength="20" rows="10" placeholder="Descreva detalhadamente a situação" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/>{!isMeeting&&<label>Fotografias<input type="file" accept="image/*,video/*,.pdf,.doc,.docx" multiple onChange={e=>setFiles(e.target.files)}/></label>}<button className="btn-primary" disabled={saving}>{saving?'Enviando...':'Enviar'}</button></form></section>;
  return <div className="dashboard-layout"><Sidebar onItemClick={navigate}/><main className="dashboard-content council-citizen-page"><header className="page-header-container"><div><h1>Vereadores</h1><p>Reuniões, demandas, visitas e conversas com os gabinetes.</p></div></header><nav className="council-citizen-nav">{TABS.map(name=><button className={tab===name?'active':''} onClick={()=>{setTab(name);setFeedback('')}} key={name}>{name}</button>)}</nav>{feedback&&<p className="council-feedback">{feedback}</p>}
  {tab==='Visão geral'&&<section><div className="council-action-grid"><button onClick={()=>setTab(TABS[1])}><LiaCalendarSolid/><strong>Solicitar reunião</strong><span>Demanda individual ou comunitária</span></button><button onClick={()=>setTab(TABS[2])}><LiaBullhornSolid/><strong>Enviar demanda</strong><span>Relato detalhado com fotografias</span></button><button onClick={()=>setTab(TABS[3])}><LiaIdCardSolid/><strong>Cadastro de visitante</strong><span>Identificação para o gabinete</span></button><button onClick={()=>setTab(TABS[4])}><LiaCommentsSolid/><strong>Mensagens</strong><span>Converse com o gabinete</span></button></div><div className="cabinet-list">{cards.map(item=><article className="data-card" key={item.id}><strong>{item.protocolo||item.id}</strong><span>{item.dadosSolicitacao?.assunto} · {item.dadosSolicitacao?.vereadorNome}</span><p>{item.dadosSolicitacao?.descricao}</p><small>{statusLabel(item.status)}</small><div className="citizen-demand-timeline">{['RECEBIDA','EM ANÁLISE','ENCAMINHADA','RESOLVIDA'].map(step=><span className={step===item.status?'current':DEMAND_STATUSES.indexOf(step)<DEMAND_STATUSES.indexOf(item.status)?'done':''} key={step}>{statusLabel(step)}</span>)}</div>{item.status==='Datas Liberadas'&&<VereadorAppointmentOffer request={item}/>}</article>)}</div></section>}
  {tab===TABS[1]&&requestForm(true)}{tab===TABS[2]&&requestForm(false)}
  {tab===TABS[3]&&<section className="data-card council-form-card"><h2>Cadastro de visitante</h2><p>Usaremos nome, contato, endereço e nascimento da sua conta. O cadastro é pessoal e não pode ser realizado para terceiros.</p><p>A selfie deve mostrar o rosto de frente, em local iluminado e sem acessórios que dificultem a identificação.</p><form onSubmit={registerVisitor}>{memberSelect(visitor.vereadorId,id=>setVisitor({vereadorId:id}))}<label>Selfie obrigatória<input type="file" required accept="image/*" capture="user" onChange={e=>setSelfie(e.target.files[0])}/></label><button className="btn-primary" disabled={saving}>{saving?'Processando...':'Finalizar cadastro'}</button></form></section>}
  {tab===TABS[4]&&<section className="data-card council-chat"><h2>Mensagens ao gabinete</h2>{memberSelect(form.vereadorId,id=>setForm({...form,...selected(id)}))}<div className="council-chat-history">{messages.filter(m=>!form.vereadorId||m.gabineteId===form.vereadorId).map(message=><p className={message.autorTipo==='cidadao'?'mine':''} key={message.id}><strong>{message.autorTipo==='cidadao'?'Você':'Gabinete'}</strong>{message.texto}</p>)}</div><form onSubmit={sendMessage}><textarea required rows="4" placeholder="Escreva sua mensagem" value={text} onChange={e=>setText(e.target.value)}/><button className="btn-primary">Enviar mensagem</button></form></section>}</main></div>;
}
