import React, {useEffect, useState} from 'react';
import {collection, onSnapshot, orderBy, query, where} from 'firebase/firestore';
import {firestore} from '../firebase';
import {useAuth} from '../contexts/FirebaseAuthContext';
import {criarProcesso} from '../services/ProcessEngine';
import AdminSidebar from '../components/AdminSidebar';

export default function ProcessProtocol({admin = false}) {
  const {currentUser} = useAuth(); const [items, setItems] = useState([]); const [types, setTypes] = useState([]); const [form, setForm] = useState({typeId:'', subject:'', description:''}); const [message, setMessage] = useState('');
  useEffect(() => onSnapshot(query(collection(firestore, 'processTypes'), where('active', '!=', false)), snap => setTypes(snap.docs.map(d => ({id:d.id, ...d.data()}))), () => setTypes([])), []);
  useEffect(() => { if (!currentUser) return undefined; const source = admin ? query(collection(firestore, 'processes'), orderBy('createdAt', 'desc')) : query(collection(firestore, 'processes'), where('requesterId', '==', currentUser.uid), orderBy('createdAt', 'desc')); return onSnapshot(source, snap => setItems(snap.docs.map(d => ({id:d.id, ...d.data()}))), () => setItems([])); }, [admin, currentUser]);
  const submit = async e => { e.preventDefault(); setMessage(''); try { const result = await criarProcesso({...form, origin: admin ? 'presencial' : 'digital'}); setMessage(`Protocolo ${result.data.protocolNumber} criado com sucesso.`); setForm({typeId:'', subject:'', description:''}); } catch (error) { setMessage(error.message || 'Não foi possível criar o protocolo.'); } };
  const count = status => items.filter(item => item.status === status).length;
  const content = <main className="dashboard-content protocol-page"><header className="page-header-container protocol-header"><div><span className="user-dashboard-eyebrow">PROCESSO ADMINISTRATIVO ELETRÔNICO</span><h1>{admin ? 'Protocolo e processos' : 'Meus protocolos'}</h1><p>{admin ? 'Gerencie todos os protocolos abertos, tramitações e pendências da Câmara.' : 'Acompanhe processos, documentos, pendências e tramitações.'}</p></div></header>{admin && <section className="protocol-metrics"><article><strong>{items.filter(item => !['Concluído','Arquivado','Cancelado'].includes(item.status)).length}</strong><span>Em andamento</span></article><article><strong>{count('Aguardando cidadão')}</strong><span>Aguardando cidadão</span></article><article><strong>{count('Concluído')}</strong><span>Concluídos</span></article><article><strong>{count('Cancelado')}</strong><span>Cancelados</span></article></section>}<section className="data-card protocol-create"><h2>{admin ? 'Novo atendimento presencial' : 'Novo protocolo'}</h2><form className="system-fields-grid" onSubmit={submit}><label>Tipo<select required value={form.typeId} onChange={e=>setForm({...form,typeId:e.target.value})}><option value="">Selecione</option>{types.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label>Assunto<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn-primary">Protocolar</button></form>{message && <p className="protocol-feedback">{message}</p>}</section><section className="protocol-workspace"><section className="data-card protocol-list"><div className="protocol-section-title"><h2>{admin ? 'Todos os processos' : 'Protocolos enviados'}</h2><span>{items.length} registro(s)</span></div>{items.map(item=><article className="protocol-row" key={item.id}><div><strong>{item.protocolNumber}</strong><small>{item.typeName || 'Processo'}</small></div><div><b>{item.subject}</b><small>{item.currentDepartmentId || 'Protocolo'}</small></div><span className={`protocol-status status-${String(item.status || '').toLowerCase().replaceAll(' ', '-')}`}>{item.status}</span></article>)}{!items.length && <p>Nenhum processo encontrado.</p>}</section>{admin && <aside className="data-card protocol-activity"><h2>Atividades recentes</h2>{items.slice(0,5).map(item=><article key={item.id}><span /><div><strong>{item.protocolNumber}</strong><p>{item.status} · {item.subject}</p></div></article>)}{!items.length && <p>As ações dos processos aparecerão aqui.</p>}</aside>}</section></main>;
  return admin ? <div className="dashboard-layout"><AdminSidebar />{content}</div> : <div className="dashboard-layout">{content}</div>;
}
