import React, {useEffect, useMemo, useRef, useState} from 'react';
import {Link, useLocation, useNavigate} from 'react-router-dom';
import {collection, limit, onSnapshot, orderBy, query, where} from 'firebase/firestore';
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
import {firestore} from '../firebase';
import {useAuth} from '../contexts/FirebaseAuthContext';
import {useSystemControl} from '../contexts/SystemControlContext';
import {anexarArquivosAoProcesso, criarProcesso} from '../services/ProcessEngine';
import AdminSidebar from '../components/AdminSidebar';
import {LiaArchiveSolid,LiaBellSolid,LiaCheckCircleSolid,LiaClipboardListSolid,LiaCogSolid,LiaFileAltSolid,LiaFolderOpenSolid,LiaHistorySolid,LiaPlusSolid,LiaStreamSolid,LiaTachometerAltSolid,LiaTrashSolid,LiaUploadSolid} from 'react-icons/lia';

pdfMake.vfs=pdfFonts?.pdfMake?.vfs||pdfFonts;
const NAV=[['','Visão geral',LiaTachometerAltSolid],['caixa-entrada','Caixa de entrada',LiaFolderOpenSolid],['processos','Todos os processos',LiaClipboardListSolid],['novo','Novo protocolo',LiaPlusSolid],['interno','Processo interno',LiaFileAltSolid],['pendencias','Pendências',LiaBellSolid],['prazos','Prazos',LiaHistorySolid],['documentos','Documentos',LiaFileAltSolid],['arquivados','Arquivados',LiaArchiveSolid],['configuracoes/tipos','Tipos de processo',LiaCogSolid],['configuracoes/fluxos','Fluxos',LiaStreamSolid],['configuracoes/modelos','Modelos',LiaFileAltSolid]];
const INITIAL={personType:'pf',requesterName:'',requesterDocument:'',requesterEmail:'',requesterPhone:'',requesterAddress:'',requesterZip:'',requesterCity:'',requesterState:'',typeId:'',subject:'',description:'',priority:'normal',accessLevel:'restricted',destinationId:'',deadlineAt:'',additionalData:{}};
const LABELS={awaiting_receipt:'Aguardando recebimento',in_progress:'Em andamento',awaiting_citizen:'Aguardando cidadão',completed:'Concluído',archived:'Arquivado',cancelled:'Cancelado',suspended:'Suspenso'};
const dateOf=value=>value?.toDate?.()||(value?new Date(value):null);
const formatDate=value=>{const date=dateOf(value);return date&&!Number.isNaN(date.getTime())?date.toLocaleDateString('pt-BR'):'—';};
const mask=value=>{const digits=String(value||'').replace(/\D/g,'');if(digits.length===11)return `***.${digits.slice(3,6)}.${digits.slice(6,9)}-**`;if(digits.length===14)return `${digits.slice(0,2)}.***.***/****-${digits.slice(-2)}`;return value||'Não informado';};
const onlyDigits=value=>String(value||'').replace(/\D/g,'');
const formatDocument=(value,kind)=>{const d=onlyDigits(value).slice(0,kind==='pj'?14:11);return kind==='pj'?d.replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1/$2').replace(/(\d{4})(\d)/,'$1-$2'):d.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')};
const formatPhone=value=>{const d=onlyDigits(value).slice(0,11);return d.length>10?d.replace(/^(\d{2})(\d{5})(\d{0,4}).*/,'($1) $2-$3'):d.replace(/^(\d{2})(\d{4})(\d{0,4}).*/,'($1) $2-$3')};
const formatZip=value=>onlyDigits(value).slice(0,8).replace(/^(\d{5})(\d)/,'$1-$2');

function SignaturePad({value,onChange}){
 const canvasRef=useRef(null),drawing=useRef(false);
 const point=event=>{const canvas=canvasRef.current,rect=canvas.getBoundingClientRect(),source=event.touches?.[0]||event;return {x:(source.clientX-rect.left)*(canvas.width/rect.width),y:(source.clientY-rect.top)*(canvas.height/rect.height)}};
 const start=event=>{event.preventDefault();const context=canvasRef.current.getContext('2d'),p=point(event);drawing.current=true;context.beginPath();context.moveTo(p.x,p.y)};
 const move=event=>{if(!drawing.current)return;event.preventDefault();const context=canvasRef.current.getContext('2d'),p=point(event);context.lineWidth=3;context.lineCap='round';context.strokeStyle='#10233f';context.lineTo(p.x,p.y);context.stroke()};
 const finish=()=>{if(!drawing.current)return;drawing.current=false;onChange(canvasRef.current.toDataURL('image/png'))};
 const clear=()=>{const canvas=canvasRef.current;canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);onChange('')};
 return <div className="protocol-signature"><div><strong>Assinatura da pessoa que está protocolando *</strong><span>Assine no espaço abaixo usando o mouse, caneta ou toque.</span></div><canvas ref={canvasRef} width="900" height="220" onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerLeave={finish}/><footer><small>{value?'Assinatura registrada.':'A assinatura é obrigatória para concluir o protocolo.'}</small><button type="button" onClick={clear}>Limpar assinatura</button></footer></div>
}

function Nav({pathname}){const navigate=useNavigate();return <aside className="protocol-module-nav"><strong>PROTOCOLO</strong>{NAV.map(([path,label,Icon])=><button type="button" key={path} className={pathname===`/admin/protocolo${path?`/${path}`:''}`?'active':''} onClick={()=>navigate(`/admin/protocolo${path?`/${path}`:''}`)}><Icon/>{label}</button>)}</aside>}

function Dashboard({items,events}){
 const now=new Date(),active=items.filter(i=>!['completed','archived','cancelled','Concluído','Arquivado','Cancelado'].includes(i.status)),late=active.filter(i=>dateOf(i.deadlineAt)&&dateOf(i.deadlineAt)<now),due=active.filter(i=>dateOf(i.deadlineAt)&&dateOf(i.deadlineAt)>=now&&dateOf(i.deadlineAt)-now<604800000);
 const metrics=[['Em andamento',active.length],['Recebidos hoje',items.filter(i=>dateOf(i.receivedAt)?.toDateString()===now.toDateString()).length],['Pendentes',items.filter(i=>['awaiting_citizen','Aguardando cidadão'].includes(i.status)).length],['Atrasados',late.length],['Concluídos',items.filter(i=>['completed','Concluído'].includes(i.status)).length],['Arquivados',items.filter(i=>['archived','Arquivado'].includes(i.status)).length]];
 const dist=field=>Object.entries(items.reduce((a,i)=>{const key=i[field]||'Não informado';a[key]=(a[key]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
 return <div className="protocol-dashboard"><section className="protocol-metrics six">{metrics.map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><section className="data-card protocol-list"><div className="protocol-section-title"><div><h2>Processos recentes</h2><p>Últimos registros e seus prazos.</p></div><Link className="btn-secondary" to="/admin/protocolo/processos">Ver todos</Link></div><div className="protocol-table-wrap"><table className="protocol-table"><thead><tr><th>Processo</th><th>Interessado</th><th>Assunto</th><th>Setor</th><th>Status</th><th>Prazo</th></tr></thead><tbody>{items.slice(0,8).map(i=><tr key={i.id}><td><Link to={`/admin/protocolo/processo/${i.id}`}>{i.protocolNumber}</Link></td><td>{i.requesterName||i.metadata?.requesterName||'—'}</td><td>{i.subject}</td><td>{i.currentDepartmentId||'Protocolo'}</td><td><span className="protocol-status">{LABELS[i.status]||i.status}</span></td><td>{formatDate(i.deadlineAt)}</td></tr>)}</tbody></table></div>{!items.length&&<div className="protocol-empty"><LiaClipboardListSolid/><h3>Nenhum processo registrado</h3><p>Os protocolos criados aparecerão aqui.</p><Link className="btn-primary" to="/admin/protocolo/novo">Criar protocolo</Link></div>}</section><section className="protocol-dashboard-grid"><article className="data-card protocol-activity"><h2>Atividades recentes</h2>{events.map(e=><div key={e.id}><span/><div><strong>{String(e.action||'Evento').replaceAll('_',' ')}</strong><p>{e.detail||'Evento registrado'} · {formatDate(e.createdAt)}</p></div></div>)}{!events.length&&<p>Nenhuma atividade recente.</p>}</article><article className="data-card"><h2>Prazos próximos</h2>{due.map(i=><Link className="protocol-mini-row" key={i.id} to={`/admin/protocolo/processo/${i.id}`}><span><strong>{i.protocolNumber}</strong>{i.subject}</span><b>{formatDate(i.deadlineAt)}</b></Link>)}{!due.length&&<p>Nenhum prazo vence nos próximos 7 dias.</p>}</article></section><section className="protocol-distributions">{[['Por setor','currentDepartmentId'],['Por tipo','typeName'],['Por status','status']].map(([title,field])=><article className="data-card" key={field}><h2>{title}</h2>{dist(field).map(([label,value])=><div className="protocol-distribution-row" key={label}><span>{field==='status'?(LABELS[label]||label):label}</span><b>{value}</b></div>)}{!items.length&&<p>Sem dados.</p>}</article>)}</section></div>
}

function Wizard({types,user,settings}){
 const navigate=useNavigate(),[step,setStep]=useState(1),[form,setForm]=useState(INITIAL),[files,setFiles]=useState([]),[signature,setSignature]=useState(''),[busy,setBusy]=useState(false),[lookup,setLookup]=useState(''),[feedback,setFeedback]=useState(''),[created,setCreated]=useState(null);const type=types.find(t=>t.id===form.typeId),fields=type?.formFields||type?.fields||[];const change=(key,value)=>setForm(current=>({...current,[key]:value}));
 const lookupCnpj=async()=>{const cnpj=form.requesterDocument.replace(/\D/g,'');if(cnpj.length!==14){setFeedback('Informe os 14 dígitos do CNPJ.');return}setLookup('cnpj');setFeedback('');try{const response=await fetch(`https://brasilapi.com.br/api/cnpj/v1/${cnpj}`);if(!response.ok)throw new Error('CNPJ não encontrado.');const data=await response.json();setForm(current=>({...current,personType:'pj',requesterName:data.razao_social||data.nome_fantasia||current.requesterName,requesterEmail:data.email||current.requesterEmail,requesterPhone:data.ddd_telefone_1||current.requesterPhone,requesterZip:data.cep||current.requesterZip,requesterAddress:[data.descricao_tipo_de_logradouro,data.logradouro,data.numero,data.complemento,data.bairro].filter(Boolean).join(', '),requesterCity:data.municipio||current.requesterCity,requesterState:data.uf||current.requesterState}));setFeedback('Dados do CNPJ preenchidos. Revise antes de continuar.')}catch(error){setFeedback(error.message||'Não foi possível consultar o CNPJ.')}finally{setLookup('')}};
 const lookupCep=async()=>{const cep=form.requesterZip.replace(/\D/g,'');if(cep.length!==8){setFeedback('Informe os 8 dígitos do CEP.');return}setLookup('cep');setFeedback('');try{const response=await fetch(`https://brasilapi.com.br/api/cep/v2/${cep}`);if(!response.ok)throw new Error('CEP não encontrado.');const data=await response.json();setForm(current=>({...current,requesterAddress:[data.street,data.neighborhood].filter(Boolean).join(', '),requesterCity:data.city||current.requesterCity,requesterState:data.state||current.requesterState}));setFeedback('Endereço preenchido pelo CEP. Complete o número e revise os dados.')}catch(error){setFeedback(error.message||'Não foi possível consultar o CEP.')}finally{setLookup('')}};
 const choose=e=>{const incoming=[...(e.target.files||[])],ok=incoming.filter(f=>['application/pdf','image/jpeg','image/png'].includes(f.type)&&f.size<=10485760);setFiles(current=>[...current,...ok]);if(ok.length!==incoming.length)setFeedback('Use somente PDF, JPG ou PNG com até 10 MB.')};
 const valid=step===1?form.requesterName&&form.requesterDocument:step===2?form.typeId&&form.subject&&form.destinationId:step===3?fields.filter(f=>f.required).every(f=>form.additionalData[f.id||f.name]):true;
 const submit=async()=>{if(!signature){setFeedback('A pessoa interessada deve assinar antes de protocolar.');return}setBusy(true);setFeedback('');try{const response=await criarProcesso({...form,requesterDocument:onlyDigits(form.requesterDocument),requesterPhone:onlyDigits(form.requesterPhone),requesterZip:onlyDigits(form.requesterZip),origin:'presencial',requesterType:form.personType,metadata:{address:form.requesterAddress,zip:onlyDigits(form.requesterZip),city:form.requesterCity,state:form.requesterState,additionalData:form.additionalData,signedByRequester:true}});const signatureBlob=await (await fetch(signature)).blob(),signatureFile=new File([signatureBlob],`assinatura-${response.data.protocolNumber}.png`,{type:'image/png'}),documents=[...files,signatureFile];await anexarArquivosAoProcesso(response.data.id,documents,form.accessLevel);setCreated({...response.data,...form,files,createdAt:new Date(),authenticationCode:`${response.data.id.slice(0,6).toUpperCase()}${response.data.protocolNumber.replace(/\D/g,'').slice(-6)}`})}catch(error){setFeedback(error.message||'Não foi possível protocolar.')}finally{setBusy(false)}};
 const receipt=print=>{const institution=settings?.tenant||{},definition={pageMargins:[48,48,48,54],content:[{text:institution.name||institution.portalTitle||'Câmara Municipal',style:'institution'},{text:'COMPROVANTE DE PROTOCOLO',style:'title'},{text:created.protocolNumber,style:'number'},...[['Data/hora',created.createdAt.toLocaleString('pt-BR')],['Interessado',created.requesterName],['CPF/CNPJ',mask(created.requesterDocument)],['Tipo',type?.name],['Assunto',created.subject],['Descrição',created.description||'Não informada'],['Documentos',created.files.map(f=>f.name).join(', ')||'Nenhum'],['Atendente',user?.displayName||user?.email||'Servidor'],['Código de autenticação',created.authenticationCode]].map(([label,value])=>({columns:[{text:label,bold:true,width:140},{text:String(value||'—')}],margin:[0,5]})),{qr:`${window.location.origin}/documento/verificar/${created.authenticationCode}`,fit:100,alignment:'center',margin:[0,20,0,6]}],footer:{text:[institution.address,institution.phone,institution.email].filter(Boolean).join(' · '),alignment:'center',fontSize:8},styles:{institution:{alignment:'center',bold:true,fontSize:13},title:{alignment:'center',bold:true,fontSize:17,margin:[0,18,0,5]},number:{alignment:'center',bold:true,fontSize:22,color:'#0864a8',margin:[0,0,0,22]}}};const pdf=pdfMake.createPdf(definition);print?pdf.print():pdf.download(`comprovante-${created.protocolNumber}.pdf`)};
 if(created)return <section className="data-card protocol-success"><LiaCheckCircleSolid/><span>PROTOCOLO REALIZADO COM SUCESSO</span><h2>{created.protocolNumber}</h2><p>O processo foi enviado para <strong>{created.destinationId}</strong>.</p><div><button className="btn-primary" onClick={()=>navigate(`/admin/protocolo/processo/${created.id}`)}>Abrir processo</button><button className="btn-secondary" onClick={()=>receipt(false)}>Baixar comprovante</button><button className="btn-secondary" onClick={()=>receipt(true)}>Imprimir</button><button className="btn-secondary" onClick={()=>{setCreated(null);setForm(INITIAL);setFiles([]);setSignature('');setStep(1)}}>Novo protocolo</button></div></section>;
 return <section className="data-card protocol-create"><div className="protocol-section-title"><div><h2>Novo protocolo presencial</h2><p>O processo será criado somente após a revisão.</p></div><span>Etapa {step} de 5</span></div><div className="protocol-stepper">{['Interessado','Protocolo','Dados específicos','Documentos','Revisão'].map((label,index)=><button type="button" key={label} className={step===index+1?'active':step>index+1?'done':''} onClick={()=>index+1<step&&setStep(index+1)}><b>{index+1}</b><span>{label}</span></button>)}</div>
 {step===1&&<div className="protocol-form-grid"><Field label="Tipo de pessoa"><select value={form.personType} onChange={e=>setForm(current=>({...current,personType:e.target.value,requesterDocument:''}))}><option value="pf">Pessoa física</option><option value="pj">Pessoa jurídica</option></select></Field><Field label="CPF/CNPJ *"><div className="protocol-lookup"><input inputMode="numeric" value={form.requesterDocument} onChange={e=>change('requesterDocument',formatDocument(e.target.value,form.personType))} placeholder={form.personType==='pj'?'00.000.000/0000-00':'000.000.000-00'}/>{form.personType==='pj'&&<button type="button" onClick={lookupCnpj} disabled={lookup==='cnpj'}>{lookup==='cnpj'?'Consultando...':'Consultar CNPJ'}</button>}</div></Field><Field label="Nome/Razão social *" wide><input value={form.requesterName} onChange={e=>change('requesterName',e.target.value)}/></Field><Field label="E-mail"><input type="email" value={form.requesterEmail} onChange={e=>change('requesterEmail',e.target.value)}/></Field><Field label="Telefone"><input inputMode="tel" value={form.requesterPhone} onChange={e=>change('requesterPhone',formatPhone(e.target.value))} placeholder="(00) 00000-0000"/></Field><Field label="CEP"><div className="protocol-lookup"><input inputMode="numeric" value={form.requesterZip} onChange={e=>change('requesterZip',formatZip(e.target.value))} placeholder="00000-000"/><button type="button" onClick={lookupCep} disabled={lookup==='cep'}>{lookup==='cep'?'Consultando...':'Buscar CEP'}</button></div></Field><Field label="Endereço" wide><input value={form.requesterAddress} onChange={e=>change('requesterAddress',e.target.value)} placeholder="Logradouro, número, complemento e bairro"/></Field><Field label="Município"><input value={form.requesterCity} onChange={e=>change('requesterCity',e.target.value)}/></Field><Field label="UF"><input maxLength="2" value={form.requesterState} onChange={e=>change('requesterState',e.target.value.toUpperCase())}/></Field></div>}
 {step===2&&<div className="protocol-form-grid"><Field label="Tipo de processo *"><select value={form.typeId} onChange={e=>{const selected=types.find(t=>t.id===e.target.value);setForm(current=>({...current,typeId:e.target.value,destinationId:selected?.initialDepartmentId||'',accessLevel:selected?.accessLevel||'restricted'}))}}><option value="">Selecione</option>{types.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></Field><Field label="Setor de destino *"><input value={form.destinationId} onChange={e=>change('destinationId',e.target.value)} placeholder="Definido pelo fluxo"/></Field><Field label="Assunto *" wide><input value={form.subject} onChange={e=>change('subject',e.target.value)}/></Field><Field label="Descrição" wide><textarea rows="5" value={form.description} onChange={e=>change('description',e.target.value)}/></Field><Field label="Prioridade"><select value={form.priority} onChange={e=>change('priority',e.target.value)}><option value="normal">Normal</option><option value="urgent">Urgente</option></select></Field><Field label="Nível de acesso"><select value={form.accessLevel} onChange={e=>change('accessLevel',e.target.value)}><option value="public">Público</option><option value="restricted">Restrito</option><option value="confidential">Sigiloso</option></select></Field><Field label="Prazo"><input type="date" value={form.deadlineAt} onChange={e=>change('deadlineAt',e.target.value)}/></Field></div>}
 {step===3&&<div className="protocol-form-grid">{fields.map(field=><Field key={field.id||field.name} label={`${field.label}${field.required?' *':''}`} wide={field.type==='textarea'}>{field.type==='textarea'?<textarea rows="4" value={form.additionalData[field.id||field.name]||''} onChange={e=>change('additionalData',{...form.additionalData,[field.id||field.name]:e.target.value})}/>:field.type==='select'?<select value={form.additionalData[field.id||field.name]||''} onChange={e=>change('additionalData',{...form.additionalData,[field.id||field.name]:e.target.value})}><option value="">Selecione</option>{(field.options||[]).map(option=><option key={option}>{option}</option>)}</select>:<input type={['date','time','number','email'].includes(field.type)?field.type:'text'} value={form.additionalData[field.id||field.name]||''} onChange={e=>change('additionalData',{...form.additionalData,[field.id||field.name]:e.target.value})}/>}</Field>)}{!fields.length&&<div className="protocol-empty span-2"><LiaFileAltSolid/><h3>Sem campos adicionais</h3><p>Este tipo não exige informações específicas.</p></div>}</div>}
 {step===4&&<div><label className="protocol-dropzone"><LiaUploadSolid/><strong>Arraste os documentos ou selecione os arquivos</strong><span>PDF, JPG, JPEG ou PNG · até 10 MB</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={choose}/></label><div className="protocol-files">{files.map((file,index)=><article key={`${file.name}-${index}`}><LiaFileAltSolid/><div><strong>{file.name}</strong><span>{(file.size/1048576).toFixed(2)} MB · pronto</span></div><button type="button" onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))}><LiaTrashSolid/></button></article>)}</div></div>}
 {step===5&&<div className="protocol-review"><section><h3>Interessado</h3><p><b>{form.requesterName}</b></p><p>{mask(form.requesterDocument)} · {form.requesterEmail||'E-mail não informado'}</p></section><section><h3>Protocolo</h3><p><b>{type?.name}</b> · {form.priority==='urgent'?'Urgente':'Normal'} · {form.accessLevel}</p><p>{form.subject}</p><p>{form.description}</p></section><section className="span-2"><h3>Destino e documentos</h3><p>{form.destinationId}</p><p>{files.length?files.map(f=>f.name).join(', '):'Nenhum documento.'}</p></section><div className="span-2"><SignaturePad value={signature} onChange={setSignature}/></div></div>}
 {feedback&&<p className="protocol-feedback">{feedback}</p>}<footer className="protocol-form-actions">{step>1?<button className="btn-secondary" type="button" onClick={()=>setStep(step-1)}>Voltar</button>:<span/>}{step<5?<button className="btn-primary" disabled={!valid} type="button" onClick={()=>setStep(step+1)}>Continuar</button>:<button className="btn-primary" disabled={busy||!signature} type="button" onClick={submit}>{busy?'Protocolando...':'PROTOCOLAR'}</button>}</footer></section>
}
const Field=({label,wide,children})=><label className={wide?'span-2':''}><span>{label}</span>{children}</label>;

export default function ProcessProtocol({admin=false}){
 const location=useLocation(),{currentUser}=useAuth(),{settings}=useSystemControl(),[items,setItems]=useState([]),[types,setTypes]=useState([]),[events,setEvents]=useState([]),isNew=location.pathname.endsWith('/novo');
 useEffect(()=>onSnapshot(query(collection(firestore,'processTypes'),where('active','!=',false)),s=>setTypes(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setTypes([])),[]);
 useEffect(()=>{if(!currentUser)return undefined;const source=admin?query(collection(firestore,'processes'),orderBy('createdAt','desc'),limit(100)):query(collection(firestore,'processes'),where('requesterId','==',currentUser.uid),orderBy('createdAt','desc'),limit(100));return onSnapshot(source,s=>setItems(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setItems([]))},[admin,currentUser]);
 useEffect(()=>admin?onSnapshot(query(collection(firestore,'processEvents'),orderBy('createdAt','desc'),limit(12)),s=>setEvents(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setEvents([])):undefined,[admin]);
 const content=useMemo(()=>isNew?<Wizard types={types} user={currentUser} settings={settings}/>:<Dashboard items={items} events={events}/>,[isNew,types,currentUser,settings,items,events]);
 const main=<main className="dashboard-content protocol-page"><header className="page-header-container protocol-header"><div><span className="user-dashboard-eyebrow">PROCESSO ADMINISTRATIVO ELETRÔNICO</span><h1>{isNew?'Novo protocolo':admin?'Protocolo e processos':'Meus protocolos'}</h1><p>{isNew?'Cadastre o interessado, os dados e os documentos apresentados.':'Gerencie protocolos, tramitações, documentos, pendências e prazos.'}</p></div></header>{admin?<div className="protocol-module-layout"><Nav pathname={location.pathname}/><div className="protocol-module-content">{content}</div></div>:content}</main>;
 return admin?<div className="dashboard-layout"><AdminSidebar/>{main}</div>:<div className="dashboard-layout">{main}</div>
}
