import React,{useEffect,useMemo,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {addDoc,collection,doc,onSnapshot,orderBy,query,serverTimestamp,setDoc,updateDoc} from 'firebase/firestore';
import {firestore} from '../firebase';
import AdminSidebar from '../components/AdminSidebar';
import {LiaArchiveSolid,LiaBellSolid,LiaClipboardListSolid,LiaCogSolid,LiaFileAltSolid,LiaFolderOpenSolid,LiaHistorySolid,LiaPlusSolid,LiaStreamSolid,LiaTachometerAltSolid} from 'react-icons/lia';

const LABELS={"caixa-entrada":"Caixa de entrada",processos:"Todos os processos",novo:"Novo protocolo",interno:"Processo interno",pendencias:"Pendências",prazos:"Prazos",documentos:"Documentos",arquivados:"Arquivados","configuracoes/tipos":"Tipos de processo","configuracoes/fluxos":"Fluxos de processo","configuracoes/modelos":"Modelos de documentos","configuracoes/numeracao":"Numeração","configuracoes/prazos":"Prazos padrão"};
const NAV=[['', 'Visão geral',LiaTachometerAltSolid],['caixa-entrada','Caixa de entrada',LiaFolderOpenSolid],['processos','Todos os processos',LiaClipboardListSolid],['novo','Novo protocolo',LiaPlusSolid],['interno','Processo interno',LiaFileAltSolid],['pendencias','Pendências',LiaBellSolid],['prazos','Prazos',LiaHistorySolid],['documentos','Documentos',LiaFileAltSolid],['arquivados','Arquivados',LiaArchiveSolid],['configuracoes/tipos','Tipos de processo',LiaCogSolid],['configuracoes/fluxos','Fluxos',LiaStreamSolid],['configuracoes/modelos','Modelos',LiaFileAltSolid],['configuracoes/numeracao','Numeração',LiaCogSolid],['configuracoes/prazos','Prazos padrão',LiaHistorySolid]];
const EMPTY={type:{name:'',code:'',category:'',description:'',defaultDeadlineDays:15,initialDepartmentId:'',accessLevel:'restricted',priority:'normal',allowCitizenOpen:true,allowInPersonOpen:true,allowInternal:true,active:true,formFields:[],requiredDocuments:[]},flow:{name:'',processTypeId:'',description:'',active:true,stepsText:'Protocolo | protocolo | 1 | receber\nAnálise | secretaria | 5 | analisar\nConclusão | protocolo | 1 | concluir'},template:{name:'',type:'Ofício',content:'',active:true},numbering:{format:'{ANO}.{SEQUENCIAL}',digits:6,restart:'annual'},deadline:{defaultDays:15,warningDays:3,workingDays:false}};
const formatDate=value=>value?.toDate?.()?.toLocaleDateString('pt-BR')||'—';

function ProtocolNav({section}){return <aside className="protocol-module-nav protocol-module-nav-fixed"><strong>PROTOCOLO</strong>{NAV.map(([path,label,Icon])=><Link key={path} className={section===path?'active':''} to={`/admin/protocolo${path?`/${path}`:''}`}><Icon/>{label}</Link>)}</aside>}

function Modal({title,onClose,children,onSave,busy}){return <div className="modal-overlay" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="modal-content protocol-config-modal" onSubmit={onSave}><div className="modal-header"><div><span className="user-dashboard-eyebrow">CONFIGURAÇÃO</span><h2>{title}</h2></div><button type="button" className="modal-close-btn" onClick={onClose}>×</button></div>{children}<footer><button type="button" className="btn-secondary" onClick={onClose}>Cancelar</button><button className="btn-primary" disabled={busy}>{busy?'Salvando...':'Salvar'}</button></footer></form></div>}

function Types({items,onEdit}){return <><div className="protocol-config-table"><div className="head"><span>Código</span><span>Nome e categoria</span><span>Prazo</span><span>Setor inicial</span><span>Status</span><span/></div>{items.map(item=><div className="row" key={item.id}><b>{item.code||'—'}</b><span><strong>{item.name}</strong><small>{item.category||'Sem categoria'}</small></span><span>{item.defaultDeadlineDays||0} dias</span><span>{item.initialDepartmentId||'Não definido'}</span><em className={item.active!==false?'on':'off'}>{item.active!==false?'Ativo':'Inativo'}</em><button onClick={()=>onEdit(item)}>Editar</button></div>)}</div>{!items.length&&<Empty title="Nenhum tipo configurado" text="Cadastre o primeiro tipo para liberar a abertura de protocolos."/>}</>}
function Flows({items,types,onEdit}){return <div className="protocol-config-cards">{items.map(item=><article key={item.id}><header><div><small>FLUXO</small><h3>{item.name}</h3></div><em className={item.active!==false?'on':'off'}>{item.active!==false?'Ativo':'Inativo'}</em></header><p>{types.find(type=>type.id===item.processTypeId)?.name||'Todos os tipos'}</p><div className="protocol-flow-preview">{(item.steps||[]).map((step,index)=><React.Fragment key={`${step.name}-${index}`}><span><b>{index+1}</b>{step.name}</span>{index<item.steps.length-1&&<i>↓</i>}</React.Fragment>)}</div><button onClick={()=>onEdit(item)}>Editar fluxo</button></article>)}{!items.length&&<Empty title="Nenhum fluxo configurado" text="Crie etapas para encaminhar processos automaticamente."/>}</div>}
function Templates({items,onEdit}){return <div className="protocol-config-cards">{items.map(item=><article key={item.id}><header><div><small>{item.type||'DOCUMENTO'}</small><h3>{item.name}</h3></div><em className={item.active!==false?'on':'off'}>{item.active!==false?'Ativo':'Inativo'}</em></header><p>{String(item.content||'Modelo sem conteúdo').replace(/<[^>]*>/g,'').slice(0,150)}</p><small>Atualizado em {formatDate(item.updatedAt)}</small><button onClick={()=>onEdit(item)}>Editar modelo</button></article>)}{!items.length&&<Empty title="Nenhum modelo cadastrado" text="Crie modelos institucionais com variáveis do processo."/>}</div>}
const Empty=({title,text})=><div className="protocol-empty"><LiaClipboardListSolid/><h3>{title}</h3><p>{text}</p></div>;

export default function ProtocolWorkspacePage(){
 const location=useLocation(),section=location.pathname.replace('/admin/protocolo/',''),[processes,setProcesses]=useState([]),[types,setTypes]=useState([]),[flows,setFlows]=useState([]),[templates,setTemplates]=useState([]),[numbering,setNumbering]=useState(EMPTY.numbering),[deadline,setDeadline]=useState(EMPTY.deadline),[modal,setModal]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
 useEffect(()=>onSnapshot(query(collection(firestore,'processes'),orderBy('createdAt','desc')),s=>setProcesses(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setProcesses([])),[]);
 useEffect(()=>onSnapshot(collection(firestore,'processTypes'),s=>setTypes(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setTypes([])),[]);
 useEffect(()=>onSnapshot(collection(firestore,'processFlows'),s=>setFlows(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setFlows([])),[]);
 useEffect(()=>onSnapshot(collection(firestore,'documentTemplates'),s=>setTemplates(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setTemplates([])),[]);
 useEffect(()=>onSnapshot(doc(firestore,'protocolSettings','numbering'),s=>s.exists()&&setNumbering(s.data())),[]);
 useEffect(()=>onSnapshot(doc(firestore,'protocolSettings','deadlines'),s=>s.exists()&&setDeadline(s.data())),[]);
 const rows=useMemo(()=>section==='arquivados'?processes.filter(p=>['archived','Arquivado'].includes(p.status)):section==='pendencias'?processes.filter(p=>['awaiting_citizen','Aguardando cidadão'].includes(p.status)):section==='prazos'?processes.filter(p=>p.deadlineAt):section==='caixa-entrada'?processes.filter(p=>['awaiting_receipt','in_progress','Protocolado','Em tramitação','Em análise'].includes(p.status)):processes,[processes,section]);
 const open=(kind,item)=>{setFeedback('');setModal(kind);if(kind==='type')setForm({...EMPTY.type,...item,fieldsText:(item?.formFields||[]).map(f=>`${f.label}|${f.type}|${f.required?'sim':'não'}|${(f.options||[]).join(',')}`).join('\n'),documentsText:(item?.requiredDocuments||[]).join('\n')});if(kind==='flow')setForm({...EMPTY.flow,...item,stepsText:(item?.steps||[]).map(s=>`${s.name}|${s.departmentId||''}|${s.deadlineDays||''}|${s.requiredAction||''}`).join('\n')||EMPTY.flow.stepsText});if(kind==='template')setForm({...EMPTY.template,...item})};
 const save=async event=>{event.preventDefault();setBusy(true);setFeedback('');try{let data;if(modal==='type'){data={...form,defaultDeadlineDays:Number(form.defaultDeadlineDays)||0,formFields:String(form.fieldsText||'').split('\n').filter(Boolean).map((line,index)=>{const [label,type='text',required,options='']=line.split('|');return{id:`field_${index+1}`,label:label.trim(),type:type.trim(),required:required.trim().toLowerCase()==='sim',options:options.split(',').map(v=>v.trim()).filter(Boolean)}}),requiredDocuments:String(form.documentsText||'').split('\n').map(v=>v.trim()).filter(Boolean),updatedAt:serverTimestamp()};delete data.fieldsText;delete data.documentsText}else if(modal==='flow'){data={...form,steps:String(form.stepsText||'').split('\n').filter(Boolean).map((line,index)=>{const [name,departmentId,deadlineDays,requiredAction]=line.split('|');return{order:index+1,name:name.trim(),departmentId:departmentId?.trim()||'',deadlineDays:Number(deadlineDays)||0,requiredAction:requiredAction?.trim()||''}}),updatedAt:serverTimestamp()};delete data.stepsText}else data={...form,updatedAt:serverTimestamp()};const target=modal==='type'?'processTypes':modal==='flow'?'processFlows':'documentTemplates';if(form.id){const id=form.id;delete data.id;await updateDoc(doc(firestore,target,id),data)}else await addDoc(collection(firestore,target),{...data,createdAt:serverTimestamp()});setModal(null);setFeedback('Configuração salva com sucesso.')}catch(error){setFeedback(error.message||'Não foi possível salvar.')}finally{setBusy(false)}};
 const saveSetting=async(kind,value)=>{setBusy(true);try{await setDoc(doc(firestore,'protocolSettings',kind),{...value,updatedAt:serverTimestamp()},{merge:true});setFeedback('Configuração salva com sucesso.')}catch(error){setFeedback(error.message||'Não foi possível salvar.')}finally{setBusy(false)}};
 const config=section.startsWith('configuracoes/'),title=LABELS[section]||'Protocolo';
 return <div className="dashboard-layout"><AdminSidebar/><main className="dashboard-content protocol-page"><header className="page-header-container protocol-header"><div><span className="user-dashboard-eyebrow">PROTOCOLO</span><h1>{title}</h1><p>Gestão integrada de processos administrativos eletrônicos.</p></div></header><div className="protocol-module-layout"><ProtocolNav section={section}/><section className="protocol-module-content">{config?<article className="data-card protocol-list protocol-config-page"><div className="protocol-section-title"><div><h2>{title}</h2><p>Configuração aplicada à abertura e tramitação dos processos.</p></div>{section.endsWith('tipos')&&<button className="btn-primary" onClick={()=>open('type')}>+ Novo tipo</button>}{section.endsWith('fluxos')&&<button className="btn-primary" onClick={()=>open('flow')}>+ Novo fluxo</button>}{section.endsWith('modelos')&&<button className="btn-primary" onClick={()=>open('template')}>+ Novo modelo</button>}</div>{section.endsWith('tipos')&&<Types items={types} onEdit={item=>open('type',item)}/>} {section.endsWith('fluxos')&&<Flows items={flows} types={types} onEdit={item=>open('flow',item)}/>} {section.endsWith('modelos')&&<Templates items={templates} onEdit={item=>open('template',item)}/>} {section.endsWith('numeracao')&&<Numbering value={numbering} onChange={setNumbering} onSave={()=>saveSetting('numbering',numbering)} busy={busy}/>} {section.endsWith('prazos')&&<Deadlines value={deadline} onChange={setDeadline} onSave={()=>saveSetting('deadlines',deadline)} busy={busy}/>} {feedback&&<p className="protocol-feedback">{feedback}</p>}</article>:<ProcessList title={title} rows={rows}/>}</section></div>{modal&&<ConfigModal kind={modal} form={form} setForm={setForm} types={types} onClose={()=>setModal(null)} onSave={save} busy={busy}/>}</main></div>
}

function ProcessList({title,rows}){return <article className="data-card protocol-list"><div className="protocol-section-title"><h2>{title}</h2><span>{rows.length} registro(s)</span></div>{rows.map(item=><Link className="protocol-row" key={item.id} to={`/admin/protocolo/processo/${item.id}`}><div><strong>{item.protocolNumber}</strong><small>{item.typeName||'Processo'}</small></div><div><b>{item.subject}</b><small>{item.currentDepartmentId||'Protocolo'}</small></div><span className="protocol-status">{item.status}</span></Link>)}{!rows.length&&<Empty title="Nenhum processo nesta seção" text="Os processos compatíveis com esta situação aparecerão aqui."/>}</article>}
function Numbering({value,onChange,onSave,busy}){const preview=`${new Date().getFullYear()}.${String(154).padStart(Number(value.digits)||6,'0')}`;return <div className="protocol-settings-form"><label><span>Formato</span><input value={value.format||''} onChange={e=>onChange({...value,format:e.target.value})}/><small>Variáveis disponíveis: {'{ANO}'} e {'{SEQUENCIAL}'}</small></label><label><span>Quantidade de dígitos</span><input type="number" min="3" max="12" value={value.digits||6} onChange={e=>onChange({...value,digits:e.target.value})}/></label><label><span>Reiniciar sequência</span><select value={value.restart||'annual'} onChange={e=>onChange({...value,restart:e.target.value})}><option value="annual">Anualmente</option><option value="never">Nunca</option></select></label><div className="protocol-number-preview"><small>PREVIEW</small><strong>{preview}</strong></div><button className="btn-primary" onClick={onSave} disabled={busy}>Salvar numeração</button></div>}
function Deadlines({value,onChange,onSave,busy}){return <div className="protocol-settings-form"><label><span>Prazo padrão em dias</span><input type="number" min="0" value={value.defaultDays||0} onChange={e=>onChange({...value,defaultDays:Number(e.target.value)})}/></label><label><span>Avisar antes do vencimento</span><input type="number" min="0" value={value.warningDays||0} onChange={e=>onChange({...value,warningDays:Number(e.target.value)})}/></label><label className="protocol-check"><input type="checkbox" checked={Boolean(value.workingDays)} onChange={e=>onChange({...value,workingDays:e.target.checked})}/><span>Contar somente dias úteis</span></label><button className="btn-primary" onClick={onSave} disabled={busy}>Salvar prazos</button></div>}
function ConfigModal({kind,form,setForm,types,onClose,onSave,busy}){const update=(key,value)=>setForm(current=>({...current,[key]:value}));if(kind==='type')return <Modal title={form.id?'Editar tipo de processo':'Novo tipo de processo'} onClose={onClose} onSave={onSave} busy={busy}><div className="protocol-form-grid"><Field label="Nome *"><input required value={form.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Código *"><input required value={form.code} onChange={e=>update('code',e.target.value.toUpperCase())}/></Field><Field label="Categoria"><input value={form.category} onChange={e=>update('category',e.target.value)}/></Field><Field label="Prazo padrão"><input type="number" value={form.defaultDeadlineDays} onChange={e=>update('defaultDeadlineDays',e.target.value)}/></Field><Field label="Setor inicial"><input value={form.initialDepartmentId} onChange={e=>update('initialDepartmentId',e.target.value)}/></Field><Field label="Acesso padrão"><select value={form.accessLevel} onChange={e=>update('accessLevel',e.target.value)}><option value="public">Público</option><option value="restricted">Restrito</option><option value="confidential">Sigiloso</option></select></Field><Field label="Descrição" wide><textarea rows="3" value={form.description} onChange={e=>update('description',e.target.value)}/></Field><Field label="Campos do formulário" wide><textarea rows="6" value={form.fieldsText} onChange={e=>update('fieldsText',e.target.value)} placeholder="Data pretendida|date|sim&#10;Tipo do evento|select|sim|Solene,Reunião,Outro"/><small>Uma linha por campo: Label | tipo | obrigatório (sim/não) | opções</small></Field><Field label="Documentos obrigatórios" wide><textarea rows="4" value={form.documentsText} onChange={e=>update('documentsText',e.target.value)} placeholder="Documento de identificação&#10;Requerimento assinado"/></Field><div className="protocol-options span-2">{[['allowCitizenOpen','Abertura online'],['allowInPersonOpen','Abertura presencial'],['allowInternal','Processo interno'],['active','Tipo ativo']].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(form[key])} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}</div></div></Modal>;
 if(kind==='flow')return <Modal title={form.id?'Editar fluxo':'Novo fluxo'} onClose={onClose} onSave={onSave} busy={busy}><div className="protocol-form-grid"><Field label="Nome *"><input required value={form.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Tipo de processo"><select value={form.processTypeId} onChange={e=>update('processTypeId',e.target.value)}><option value="">Todos</option>{types.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select></Field><Field label="Descrição" wide><textarea rows="3" value={form.description} onChange={e=>update('description',e.target.value)}/></Field><Field label="Etapas do fluxo" wide><textarea rows="9" value={form.stepsText} onChange={e=>update('stepsText',e.target.value)}/><small>Uma etapa por linha: Nome | setor | prazo em dias | ação obrigatória</small></Field><label className="protocol-check span-2"><input type="checkbox" checked={Boolean(form.active)} onChange={e=>update('active',e.target.checked)}/><span>Fluxo ativo</span></label></div></Modal>;
 return <Modal title={form.id?'Editar modelo':'Novo modelo de documento'} onClose={onClose} onSave={onSave} busy={busy}><div className="protocol-form-grid"><Field label="Nome *"><input required value={form.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Tipo"><select value={form.type} onChange={e=>update('type',e.target.value)}>{['Ofício','Despacho','Memorando','Parecer','Certidão','Declaração','Encaminhamento','Comunicação interna','Outro'].map(type=><option key={type}>{type}</option>)}</select></Field><Field label="Conteúdo do modelo" wide><textarea rows="14" value={form.content} onChange={e=>update('content',e.target.value)} placeholder="Prezado(a) {{interessado}}, ..."/><small>{'Variáveis: {{numero_processo}}, {{interessado}}, {{assunto}}, {{data}}, {{camara}}, {{servidor}}, {{setor}}'}</small></Field><label className="protocol-check span-2"><input type="checkbox" checked={Boolean(form.active)} onChange={e=>update('active',e.target.checked)}/><span>Modelo ativo</span></label></div></Modal>}
const Field=({label,wide,children})=><label className={wide?'span-2':''}><span>{label}</span>{children}</label>;
