import React, { useEffect, useState } from 'react';
import { addDoc, collection, onSnapshot, query, serverTimestamp, updateDoc, doc, where } from 'firebase/firestore';
import { firestore } from '../firebase';

export default function CabinetReceivedLetters({ gabineteId, canOperate }) {
  const [letters, setLetters] = useState([]); const [filter, setFilter] = useState('Todos');
  useEffect(() => { if (!gabineteId) return undefined; return onSnapshot(query(collection(firestore, 'gabinetes-oficios-recebidos'), where('gabineteId', '==', gabineteId)), snap => setLetters(snap.docs.map(item => ({ id: item.id, ...item.data() })))); }, [gabineteId]);
  const transform = async item => { if (!canOperate || item.demandaId) return; const result = await addDoc(collection(firestore, 'solicitacoes-vereadores'), { gabineteId, userId: item.userId, dadosUsuario: item.dadosUsuario || {}, dadosSolicitacao: { assunto: item.assunto, descricao: item.mensagem || '', origem: 'Ofício recebido', oficioRecebidoId: item.id }, tipoDemanda: 'Ofício recebido', status: 'RECEBIDA', prioridade: 'Normal', anexos: item.anexos || [], oficioRecebidoId: item.id, dataSolicitacao: serverTimestamp() }); await updateDoc(doc(firestore, 'gabinetes-oficios-recebidos', item.id), { demandaId: result.id, status: 'EM ANÁLISE', atualizadoEm: serverTimestamp() }); };
  const visible = letters.filter(item => filter === 'Todos' || item.status === filter);
  return <section className="data-card"><div className="cabinet-section-heading"><div><h2>Ofícios recebidos</h2><p>Protocolos enviados pelos cidadãos ao gabinete.</p></div><select value={filter} onChange={event => setFilter(event.target.value)}><option>Todos</option><option>RECEBIDO</option><option>EM ANÁLISE</option><option>ENCAMINHADO</option><option>RESPONDIDO</option><option>CONCLUÍDO</option><option>ARQUIVADO</option></select></div><div className="cabinet-list">{visible.map(item => <article className="cabinet-event-row" key={item.id}><div><strong>{item.protocolo}</strong><p>{item.assunto}</p><small>{item.dadosUsuario?.name || item.dadosUsuario?.email || 'Cidadão'} · {item.status}</small></div><div className="form-row">{item.anexos?.map((url, index) => <a key={url} href={url} target="_blank" rel="noreferrer">Anexo {index + 1}</a>)}{canOperate && !item.demandaId && <button type="button" className="btn-primary cabinet-small-button" onClick={() => transform(item)}>Transformar em demanda</button>}</div></article>)}{!visible.length && <p>Nenhum ofício recebido.</p>}</div></section>;
}
