import CabinetOverlay from './CabinetOverlay';
import React, { useEffect, useState } from 'react';
import { addDoc, collection, onSnapshot, query, serverTimestamp, where } from 'firebase/firestore';
import { firestore } from '../firebase';

export default function CabinetCommunication({ gabineteId, canOperate }) {
  const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ title: '', message: '', link: '', channels: ['app'] });
  useEffect(() => { if (!gabineteId) return undefined; return onSnapshot(query(collection(firestore, 'gabinetes-comunicacoes'), where('gabineteId', '==', gabineteId)), snap => setItems(snap.docs.map(item => ({ id: item.id, ...item.data() })).sort((a, b) => (b.criadoEm?.toMillis?.() || 0) - (a.criadoEm?.toMillis?.() || 0)))); }, [gabineteId]);
  const toggle = channel => setForm(current => ({ ...current, channels: current.channels.includes(channel) ? current.channels.filter(item => item !== channel) : [...current.channels, channel] }));
  const save = async event => { event.preventDefault(); if (!form.title.trim() || !form.message.trim() || !form.channels.length) return; await addDoc(collection(firestore, 'gabinetes-comunicacoes'), { ...form, titulo: form.title.trim(), mensagem: form.message.trim(), gabineteId, status: 'ENVIADA', criadoEm: serverTimestamp(), enviadoPor: gabineteId, destinatarios: 'contatos habilitados' }); setForm({ title: '', message: '', link: '', channels: ['app'] }); setOpen(false); };
  return <section className="data-card cabinet-communication"><div className="cabinet-section-heading"><div><h2>Comunicação</h2><p>Envie comunicados institucionais aos contatos habilitados do gabinete.</p></div>{canOperate && <button type="button" className="btn-primary cabinet-small-button" onClick={() => setOpen(true)}>Nova comunicação</button>}</div><div className="cabinet-list">{items.map(item => <article className="cabinet-event-row" key={item.id}><div><strong>{item.titulo}</strong><p>{item.mensagem}</p></div><small>{item.status} · {(item.channels || []).join(', ')}</small></article>)}{!items.length && <p>Nenhuma comunicação enviada.</p>}</div>{open && <CabinetOverlay><div className="modal-content cabinet-action-modal"><div className="modal-header"><h3>Nova comunicação</h3><button className="modal-close-btn" onClick={() => setOpen(false)}>×</button></div><form className="cabinet-modal-form" onSubmit={save}><input required placeholder="Título" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /><textarea required rows="6" placeholder="Mensagem" value={form.message} onChange={event => setForm({ ...form, message: event.target.value })} /><input type="url" placeholder="Link opcional" value={form.link} onChange={event => setForm({ ...form, link: event.target.value })} /><fieldset><legend>Canais</legend>{[['app','Notificação no aplicativo'],['push','Push'],['email','E-mail']].map(([id,label]) => <label key={id}><input type="checkbox" checked={form.channels.includes(id)} onChange={() => toggle(id)} /> {label}</label>)}</fieldset><button className="btn-primary">Confirmar envio</button></form></div></CabinetOverlay>}</section>;
}
