import React, { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, setDoc, updateDoc, where, writeBatch } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
import { firestore, functions } from '../firebase';
import CabinetMap from './CabinetMap';
import { DEMAND_PRIORITIES, DEMAND_STATUSES, statusLabel } from '../config/cabinetMandate';
pdfMake.vfs = pdfFonts.vfs;

const NAV = ['Visão geral','Agendamentos','Demandas','Visitantes','Conversas','Mapa','Relatórios','Minha equipe','Tarefas','Aniversariantes','Eventos'];
const birthdayToday = person => { const date = person.birthDate || person.dataNascimento || person.nascimento; const parsed=date?.toDate?.() || (date?new Date(date):null); const now=new Date(); return parsed&&parsed.getDate()===now.getDate()&&parsed.getMonth()===now.getMonth(); };
const csv = value => `"${String(value ?? '').replaceAll('"','""')}"`;
const Modal = ({ title, close, children }) => <div className="modal-overlay" onMouseDown={event=>event.target===event.currentTarget&&close()}><div className="modal-content cabinet-action-modal"><div className="modal-header"><h3>{title}</h3><button className="modal-close-btn" onClick={close}>×</button></div><div className="modal-body">{children}</div></div></div>;

export default function CabinetWorkspace({ gabineteId, items, canManageTeam, canApprove, canOperate, onOpenAvailability, onAnalyze, onChangeStatus, busy }) {
    const [view,setView]=useState('Visão geral'), [team,setTeam]=useState([]), [tasks,setTasks]=useState([]), [events,setEvents]=useState([]), [lists,setLists]=useState([]), [messages,setMessages]=useState([]), [messageText,setMessageText]=useState(''), [activeConversation,setActiveConversation]=useState('');
    const [modal,setModal]=useState(null), [error,setError]=useState(''), [saving,setSaving]=useState(false), [foundUser,setFoundUser]=useState(null), [demandMode,setDemandMode]=useState('Lista'), [demandSearch,setDemandSearch]=useState(''), [demandStatus,setDemandStatus]=useState('Todos');
    const [teamForm,setTeamForm]=useState({email:'',access:'operacional'}), [taskForm,setTaskForm]=useState({title:'',description:'',listId:'',dateTime:'',noticeHours:2}), [eventForm,setEventForm]=useState({title:'',description:'',dateTime:'',noticeHours:2}), [newList,setNewList]=useState('');
    useEffect(()=>{ if(!gabineteId)return undefined; const listen=(name,setter)=>onSnapshot(query(collection(firestore,name),where('gabineteId','==',gabineteId)),snap=>setter(snap.docs.map(row=>({id:row.id,...row.data()}))),()=>setError('Não foi possível carregar os dados deste gabinete.')); const stops=[listen('gabinetes-equipe',setTeam),listen('gabinetes-tarefas',setTasks),listen('gabinetes-eventos',setEvents),listen('gabinetes-listas',setLists),listen('gabinetes-mensagens',setMessages)]; return()=>stops.forEach(stop=>stop()); },[gabineteId]);
    const visitors=useMemo(()=>[...new Map(items.map(item=>[item.userId||item.dadosUsuario?.email||item.id,{id:item.userId||item.id,...item.dadosUsuario}])).values()],[items]);
    const appointments=items.filter(item=>item.appointmentDate||['Datas Liberadas','Agendado'].includes(item.status));
    const demands=items.filter(item=>(item.tipoDemanda||item.dadosSolicitacao?.categoriaDemanda||'Atendimento no gabinete')!=='Atendimento no gabinete').map(item=>({...item,address:item.dadosUsuario?.address||item.dadosUsuario?.endereco}));
    const close=()=>{setModal(null);setError('');setFoundUser(null)};
    const searchUser=async event=>{event.preventDefault();setSaving(true);setError('');try{const result=await httpsCallable(functions,'buscarUsuarioParaGabinete')({email:teamForm.email.trim().toLowerCase()});if(!result.data.found)throw new Error('Nenhum usuário encontrado com este e-mail.');setFoundUser(result.data.user);}catch(err){setError(err.message)}finally{setSaving(false)}};
    const requireCabinet=()=>{if(gabineteId)return true;setError('Selecione ou aguarde o carregamento de um gabinete antes de continuar.');return false};
    const confirmTeam=async()=>{if(!foundUser||!requireCabinet())return;setSaving(true);try{await setDoc(doc(firestore,'gabinetes-equipe',`${gabineteId}_${foundUser.id}`),{gabineteId,vereadorId:gabineteId,userId:foundUser.id,email:foundUser.email||teamForm.email.trim().toLowerCase(),nome:foundUser.name||foundUser.email,nivelAcesso:teamForm.access,ativo:true,criadoEm:serverTimestamp()});setTeamForm({email:'',access:'operacional'});close()}catch(err){setError(err.message)}finally{setSaving(false)}};
    const addList=async event=>{event.preventDefault();if(!newList.trim()||!requireCabinet())return;setSaving(true);setError('');try{await addDoc(collection(firestore,'gabinetes-listas'),{gabineteId,titulo:newList.trim(),ordem:lists.length,criadoEm:serverTimestamp()});setNewList('');close()}catch(err){setError(err.code==='permission-denied'?'Seu nível de acesso não permite criar listas ou as regras ainda não foram publicadas.':err.message)}finally{setSaving(false)}};
    const addTask=async event=>{event.preventDefault();if(!taskForm.title.trim()||!requireCabinet())return;setSaving(true);try{await addDoc(collection(firestore,'gabinetes-tarefas'),{gabineteId,listaId:taskForm.listId,titulo:taskForm.title.trim(),descricao:taskForm.description.trim(),dataHora:taskForm.dateTime||null,antecedenciaHoras:Number(taskForm.noticeHours)||0,status:'A fazer',ordem:tasks.filter(task=>task.listaId===taskForm.listId).length,criadoEm:serverTimestamp()});setTaskForm({title:'',description:'',listId:'',dateTime:'',noticeHours:2});close()}catch(err){setError(err.message)}finally{setSaving(false)}};
    const addEvent=async event=>{event.preventDefault();if(!eventForm.title.trim()||!eventForm.dateTime||!requireCabinet())return;setSaving(true);try{await addDoc(collection(firestore,'gabinetes-eventos'),{gabineteId,titulo:eventForm.title.trim(),descricao:eventForm.description.trim(),data:eventForm.dateTime.slice(0,10),dataHora:eventForm.dateTime,antecedenciaHoras:Number(eventForm.noticeHours)||0,status:'Agendado',criadoEm:serverTimestamp()});setEventForm({title:'',description:'',dateTime:'',noticeHours:2});close()}catch(err){setError(err.message)}finally{setSaving(false)}};
    const moveTask=(taskId,listId)=>taskId&&updateDoc(doc(firestore,'gabinetes-tarefas',taskId),{listaId:listId,atualizadoEm:serverTimestamp()});
    const changeDemand=async(item,patch)=>{if(!canOperate||!item?.id)return;setSaving(true);try{const next=patch.status||item.status;await updateDoc(doc(firestore,'solicitacoes-vereadores',item.id),{...patch,ultimaAtualizacao:serverTimestamp(),atualizadoPor:gabineteId});await addDoc(collection(firestore,'gabinetes-demandas-historico'),{gabineteId,demandaId:item.id,acao:patch.status?`Status alterado para ${next}`:'Demanda atualizada',alteracoes:patch,usuarioId:gabineteId,criadoEm:serverTimestamp()})}catch(err){setError(err.message)}finally{setSaving(false)}};
    const conversations=useMemo(()=>[...new Map(messages.map(message=>[message.userId,{userId:message.userId,name:message.nomeUsuario||message.userId}])).values()],[messages]);
    const reply=async event=>{event.preventDefault();if(!activeConversation||!messageText.trim()||!requireCabinet())return;await addDoc(collection(firestore,'gabinetes-mensagens'),{gabineteId,userId:activeConversation,nomeUsuario:conversations.find(item=>item.userId===activeConversation)?.name||'',texto:messageText.trim(),autorTipo:'gabinete',criadoEm:serverTimestamp()});setMessageText('')};
    const reportRows=type=>type==='Visitantes'?visitors:type==='Demandas'?demands:type==='Agendamentos'?appointments:tasks;
    const filteredDemands=demands.filter(item=>(demandStatus==='Todos'||item.status===demandStatus)&&(!demandSearch||`${item.protocolo||''} ${item.dadosUsuario?.name||''} ${item.dadosSolicitacao?.assunto||''} ${item.dadosUsuario?.neighborhood||''}`.toLowerCase().includes(demandSearch.toLowerCase())));
    const exportReport=(type,format)=>{const rows=reportRows(type).map(row=>[type,row.name||row.dadosUsuario?.name||row.titulo||'',row.status||'',row.appointmentDate||row.data||'']);if(format==='PDF'){pdfMake.createPdf({content:[{text:`Relatório de ${type}`,style:'header'},{table:{headerRows:1,widths:['*','*','auto','auto'],body:[['Tipo','Nome','Status','Data'],...rows]} }],styles:{header:{fontSize:18,bold:true,margin:[0,0,0,16]}}}).download(`gabinete-${type.toLowerCase()}.pdf`)}else{const content=[['Tipo','Nome','Status','Data'],...rows].map(row=>row.map(csv).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));link.download=`gabinete-${type.toLowerCase()}.csv`;link.click();URL.revokeObjectURL(link.href)}close()};
    const notifyNoShow=async item=>{if(!item.userId)return;const batch=writeBatch(firestore);batch.set(doc(collection(firestore,'notifications')),{isRead:false,targetUserId:item.userId,userId:item.userId,userEmail:item.dadosUsuario?.email||'',protocolo:item.id,timestamp:serverTimestamp(),tituloNotification:'Imprevisto no atendimento com vereador',descricaoNotification:'Houve um imprevisto e o vereador não poderá comparecer. O gabinete entrará em contato para remarcar.',source:'gabinete'});batch.update(doc(firestore,'solicitacoes-vereadores',item.id),{status:'Remarcação necessária',imprevistoEm:serverTimestamp()});await batch.commit()};
    const cards=source=><div className="cabinet-list">{source.map(item=><article className="data-card" key={item.id}><strong>{item.protocolo||item.id}</strong><span>{item.dadosUsuario?.name||item.name||item.titulo||'Cidadão'} · {item.tipoDemanda||item.dadosSolicitacao?.categoriaDemanda||item.dadosSolicitacao?.assunto}</span><p>{item.dadosSolicitacao?.descricao||item.descricao||item.address}</p><small>{item.status&&DEMAND_STATUSES.includes(item.status)?statusLabel(item.status):(item.status||item.email)}</small>{demands.includes(item)&&<div className="cabinet-demand-controls"><select value={item.status||'RECEBIDA'} onChange={event=>changeDemand(item,{status:event.target.value})}>{DEMAND_STATUSES.map(status=><option key={status} value={status}>{statusLabel(status)}</option>)}</select><select value={item.prioridade||'Normal'} onChange={event=>changeDemand(item,{prioridade:event.target.value})}>{DEMAND_PRIORITIES.map(priority=><option key={priority}>{priority}</option>)}</select><select value={item.responsavelId||''} onChange={event=>changeDemand(item,{responsavelId:event.target.value})}><option value="">Sem responsável</option>{team.map(member=><option key={member.userId} value={member.userId}>{member.nome}</option>)}</select></div>}{canApprove&&['Aguardando Análise','Aguardando Confirmação','Datas Liberadas'].includes(item.status)&&<button className="btn-primary cabinet-small-button" onClick={()=>onAnalyze(item)}>Analisar</button>}{canOperate&&item.status==='Agendado'&&<div className="form-row"><button className="cabinet-small-button" disabled={busy} onClick={()=>onChangeStatus(item,'Realizado')}>Concluir</button><button className="btn-secondary cabinet-small-button" onClick={()=>notifyNoShow(item)}>Informar imprevisto</button></div>}</article>)}</div>;
    return <div className="cabinet-workspace"><aside className="cabinet-sidemenu">{NAV.map(name=><button key={name} className={view===name?'active':''} onClick={()=>setView(name)}>{name}</button>)}</aside><div className="cabinet-view">{error&&!modal&&<p role="alert">{error}</p>}
        {view==='Visão geral'&&<div className="cabinet-kpis"><article><span>Solicitações</span><strong>{items.length}</strong></article><article><span>Demandas</span><strong>{demands.length}</strong></article><article><span>Agendamentos</span><strong>{appointments.length}</strong></article><article><span>Visitantes</span><strong>{visitors.length}</strong></article></div>}
        {view==='Agendamentos'&&<><div className="cabinet-section-heading"><div><h2>Agendamentos deste gabinete</h2><p>Os horários são exclusivos deste gabinete.</p></div>{canOperate&&<button className="btn-secondary cabinet-small-button" onClick={onOpenAvailability}>Definir horários</button>}</div>{cards(appointments)}</>}
        {view==='Demandas'&&<section><div className="cabinet-section-heading"><div><h2>Central de demandas</h2><p>Lista operacional por status, prioridade e responsável.</p></div><div className="cabinet-demand-toolbar"><input placeholder="Buscar protocolo, cidadão ou bairro" value={demandSearch} onChange={event=>setDemandSearch(event.target.value)}/><select value={demandStatus} onChange={event=>setDemandStatus(event.target.value)}><option>Todos</option>{DEMAND_STATUSES.map(status=><option key={status}>{status}</option>)}</select><button className={demandMode==='Kanban'?'btn-primary':'btn-secondary'} onClick={()=>setDemandMode(demandMode==='Kanban'?'Lista':'Kanban')}>{demandMode}</button></div></div>{demandMode==='Lista'?cards(filteredDemands):<div className="cabinet-demand-kanban">{DEMAND_STATUSES.slice(0,7).map(status=><section className="cabinet-board-list" key={status}><h3>{statusLabel(status)}</h3>{filteredDemands.filter(item=>item.status===status).map(item=><article key={item.id}><strong>{item.protocolo||item.id}</strong><p>{item.dadosSolicitacao?.assunto}</p></article>)}</section>)}</div>}</section>} {view==='Visitantes'&&cards(visitors)} {view==='Conversas'&&<section className="data-card cabinet-chat"><div className="cabinet-section-heading"><div><h2>Conversas com cidadãos</h2><p>Responda às mensagens destinadas a este gabinete.</p></div></div><div className="cabinet-chat-layout"><aside>{conversations.map(item=><button className={activeConversation===item.userId?'active':''} key={item.userId} onClick={()=>setActiveConversation(item.userId)}>{item.name}</button>)}</aside><div><div className="council-chat-history">{messages.filter(message=>message.userId===activeConversation).sort((a,b)=>(a.criadoEm?.toMillis?.()||0)-(b.criadoEm?.toMillis?.()||0)).map(message=><p className={message.autorTipo==='gabinete'?'mine':''} key={message.id}><strong>{message.autorTipo==='gabinete'?'Gabinete':message.nomeUsuario||'Cidadão'}</strong>{message.texto}</p>)}</div>{activeConversation&&<form onSubmit={reply}><textarea required rows="4" value={messageText} onChange={event=>setMessageText(event.target.value)} placeholder="Escreva a resposta"/><button className="btn-primary">Enviar resposta</button></form>}</div></div></section>} {view==='Mapa'&&<CabinetMap visitors={visitors} demands={demands}/>} 
        {view==='Relatórios'&&<section className="data-card"><h2>Relatórios</h2><div className="cabinet-report-buttons">{['Visitantes','Demandas','Agendamentos','Tarefas'].map(type=><button key={type} className="btn-secondary" onClick={()=>setModal({type:'report',report:type})}>Relatório de {type.toLowerCase()}</button>)}</div></section>}
        {view==='Minha equipe'&&<section className="data-card"><div className="cabinet-section-heading"><div><h2>Minha equipe</h2><p>Localize um usuário cadastrado pelo e-mail e defina seu acesso.</p></div>{canManageTeam&&<button className="btn-secondary cabinet-small-button" disabled={!gabineteId} onClick={()=>setModal({type:'team'})}>Localizar usuário</button>}</div>{!gabineteId&&<p>Carregando o gabinete…</p>}{team.map(member=><article className="cabinet-team-row" key={member.id}><div><strong>{member.nome}</strong><span>{member.email} · {member.nivelAcesso||'Operacional'}</span></div>{canManageTeam&&<button onClick={()=>deleteDoc(doc(firestore,'gabinetes-equipe',member.id))}>Remover</button>}</article>)}</section>}
        {view==='Tarefas'&&<section><div className="cabinet-section-heading"><div><h2>Quadro de tarefas</h2><p>Arraste os cartões entre as listas.</p></div>{canOperate&&<button className="btn-secondary cabinet-small-button" onClick={()=>setModal({type:'list'})}>Nova lista</button>}</div><div className="cabinet-board">{lists.map(list=><section key={list.id} className="cabinet-board-list" onDragOver={event=>canOperate&&event.preventDefault()} onDrop={event=>canOperate&&moveTask(event.dataTransfer.getData('text/task-id'),list.id)}><h3>{list.titulo}</h3>{tasks.filter(task=>task.listaId===list.id).map(task=><article draggable={canOperate} onDragStart={event=>event.dataTransfer.setData('text/task-id',task.id)} key={task.id}><strong>{task.titulo}</strong><p>{task.descricao}</p></article>)}{canOperate&&<button className="cabinet-add-card" onClick={()=>{setTaskForm({...taskForm,listId:list.id});setModal({type:'task'})}}>+ Adicionar cartão</button>}</section>)}</div></section>}
        {view==='Aniversariantes'&&<section className="data-card"><h2>Aniversariantes do dia</h2>{visitors.filter(birthdayToday).map(person=><p key={person.id}><strong>{person.name}</strong> · {person.phone||person.email}</p>)}{!visitors.some(birthdayToday)&&<p>Nenhum aniversariante identificado hoje.</p>}</section>}
        {view==='Eventos'&&<section className="data-card"><div className="cabinet-section-heading"><div><h2>Eventos</h2><p>Agenda institucional do gabinete.</p></div>{canOperate&&<button className="btn-secondary cabinet-small-button" onClick={()=>setModal({type:'event'})}>Novo evento</button>}</div>{events.sort((a,b)=>String(a.data).localeCompare(String(b.data))).map(event=><article className="cabinet-event-row" key={event.id}><time>{event.data?.split('-').reverse().join('/')}</time><div><strong>{event.titulo}</strong><p>{event.descricao}</p></div></article>)}</section>}
    </div>
    {modal?.type==='team'&&<Modal title="Adicionar membro ao gabinete" close={close}><form className="cabinet-modal-form" onSubmit={searchUser}><label>E-mail do usuário<input type="email" required value={teamForm.email} onChange={event=>{setFoundUser(null);setTeamForm({...teamForm,email:event.target.value})}}/></label><label>Nível de acesso<select value={teamForm.access} onChange={event=>setTeamForm({...teamForm,access:event.target.value})}><option value="consulta">Somente consulta</option><option value="operacional">Operacional</option><option value="gestao">Gestão do gabinete</option></select></label>{error&&<p role="alert">{error}</p>}{foundUser?<div className="cabinet-user-result"><strong>{foundUser.name||foundUser.email}</strong><span>{foundUser.email}</span><button type="button" className="btn-primary" onClick={confirmTeam} disabled={saving}>Confirmar assessor</button></div>:<button className="btn-primary" disabled={saving}>{saving?'Buscando...':'Buscar usuário'}</button>}</form></Modal>}
    {modal?.type==='list'&&<Modal title="Criar lista" close={close}><form className="cabinet-modal-form" onSubmit={addList}><label>Nome da lista<input autoFocus required value={newList} onChange={event=>setNewList(event.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={saving}>{saving?'Criando...':'Criar lista'}</button></form></Modal>}
    {modal?.type==='task'&&<Modal title="Adicionar cartão" close={close}><form className="cabinet-modal-form" onSubmit={addTask}><label>Título<input autoFocus required value={taskForm.title} onChange={event=>setTaskForm({...taskForm,title:event.target.value})}/></label><label>Descrição<textarea value={taskForm.description} onChange={event=>setTaskForm({...taskForm,description:event.target.value})}/></label><label>Prazo e horário<input type="datetime-local" value={taskForm.dateTime} onChange={event=>setTaskForm({...taskForm,dateTime:event.target.value})}/></label><label>Notificar com antecedência (horas)<input type="number" min="0" max="168" value={taskForm.noticeHours} onChange={event=>setTaskForm({...taskForm,noticeHours:event.target.value})}/></label>{error&&<p role="alert">{error}</p>}<button className="btn-primary" disabled={saving}>Adicionar cartão</button></form></Modal>}
    {modal?.type==='event'&&<Modal title="Novo evento" close={close}><form className="cabinet-modal-form" onSubmit={addEvent}><label>Título<input required value={eventForm.title} onChange={event=>setEventForm({...eventForm,title:event.target.value})}/></label><label>Data e horário<input type="datetime-local" required value={eventForm.dateTime} onChange={event=>setEventForm({...eventForm,dateTime:event.target.value})}/></label><label>Notificar com antecedência (horas)<input type="number" min="0" max="168" value={eventForm.noticeHours} onChange={event=>setEventForm({...eventForm,noticeHours:event.target.value})}/></label><label>Descrição<textarea value={eventForm.description} onChange={event=>setEventForm({...eventForm,description:event.target.value})}/></label><button className="btn-primary" disabled={saving}>Salvar evento</button></form></Modal>}
    {modal?.type==='report'&&<Modal title={`Relatório de ${modal.report.toLowerCase()}`} close={close}><p>Escolha o formato do arquivo.</p><div className="cabinet-report-buttons"><button className="btn-secondary" onClick={()=>exportReport(modal.report,'CSV')}>Baixar CSV</button><button className="btn-primary" onClick={()=>exportReport(modal.report,'PDF')}>Baixar PDF</button></div></Modal>}
    </div>;
}
