import React, { useState } from 'react';
import { LiaCheckCircleSolid, LiaCloudDownloadAltSolid, LiaCodeSolid, LiaExclamationTriangleSolid, LiaPlusSolid, LiaSaveSolid, LiaTimesSolid, LiaTrashAltSolid } from 'react-icons/lia';
import { fetchExternalIntegration } from '../utils/externalApiAdapter';

const TARGETS = ['noticias','vereadores','piel','tv-camara-playlist','balcao-cidadao','procon-fornecedores'];
const TYPES = ['string','number','boolean','date','array'];
const createIntegration = () => ({ id: crypto.randomUUID?.() || `api-${Date.now()}`, name: 'Notícias externas', target: 'noticias', url: '', responsePath: '', active: true, mappings: [{ targetField: 'titulo', sourceField: 'string_titulo_da_API', type: 'string' }, { targetField: 'descricao', sourceField: 'string_descricao_da_API', type: 'string' }, { targetField: 'imagemUrl', sourceField: 'imagem.url', type: 'string' }] });

const ExternalApiManager = ({ integrations = [], onChange }) => {
    const [selectedId, setSelectedId] = useState(integrations[0]?.id || '');
    const [testState, setTestState] = useState({ loading: false, error: '', data: null });
    const selected = integrations.find(item => item.id === selectedId);
    const updateSelected = patch => onChange(integrations.map(item => item.id === selectedId ? { ...item, ...patch } : item));
    const addIntegration = () => { const item = createIntegration(); onChange([...integrations, item]); setSelectedId(item.id); setTestState({ loading: false, error: '', data: null }); };
    const removeIntegration = () => { onChange(integrations.filter(item => item.id !== selectedId)); setSelectedId(''); setTestState({ loading: false, error: '', data: null }); };
    const updateMapping = (index, patch) => updateSelected({ mappings: selected.mappings.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
    const test = async () => { setTestState({ loading: true, error: '', data: null }); try { const data = await fetchExternalIntegration(selected); setTestState({ loading: false, error: '', data }); } catch (error) { setTestState({ loading: false, error: error.message || 'Não foi possível consultar a API. Verifique a URL e o CORS.', data: null }); } };

    return <div className="external-api-manager">
        <header className="external-api-heading"><div><span><LiaCodeSolid /> Adaptador de APIs</span><h2>Integrações externas</h2><p>Converta campos de outras APIs para os modelos utilizados pelo portal, sem migrar ou duplicar dados.</p></div><button onClick={addIntegration}><LiaPlusSolid /> Nova integração</button></header>
        <div className="system-readonly-note"><LiaExclamationTriangleSolid /><div><strong>Não inclua tokens na URL</strong><span>Esta configuração faz parte do CMS. APIs autenticadas devem usar uma Cloud Function intermediária e secrets protegidos.</span></div></div>
        <div className="external-api-layout">
            <aside>{integrations.map(item => <button key={item.id} className={item.id === selectedId ? 'active' : ''} onClick={() => { setSelectedId(item.id); setTestState({ loading: false, error: '', data: null }); }}><span>{item.name || 'Integração sem nome'}</span><small>{item.target} · {item.active ? 'Ativa' : 'Pausada'}</small></button>)}{!integrations.length && <div><LiaCloudDownloadAltSolid /><strong>Nenhuma API cadastrada</strong><span>Crie uma integração para mapear os primeiros campos.</span></div>}</aside>
            <section>{selected ? <><div className="external-api-form-grid"><label><span>Nome da integração</span><input value={selected.name} onChange={event => updateSelected({ name: event.target.value })} /></label><label><span>Modelo de destino</span><select value={selected.target} onChange={event => updateSelected({ target: event.target.value })}>{TARGETS.map(value => <option key={value}>{value}</option>)}</select></label><label className="wide"><span>URL da API externa</span><input type="url" value={selected.url} onChange={event => updateSelected({ url: event.target.value })} placeholder="https://api.exemplo.gov.br/noticias" /></label><label><span>Caminho da lista na resposta</span><input value={selected.responsePath} onChange={event => updateSelected({ responsePath: event.target.value })} placeholder="data.items (vazio usa a raiz)" /></label><label className="external-api-active"><input type="checkbox" checked={selected.active} onChange={event => updateSelected({ active: event.target.checked })} /><span>Integração ativa</span></label></div>
                <div className="external-mapping-heading"><div><h3>Mapeamento de campos</h3><p>Campo interno ← caminho recebido da API</p></div><button onClick={() => updateSelected({ mappings: [...selected.mappings, { targetField: '', sourceField: '', type: 'string' }] })}><LiaPlusSolid /> Campo</button></div>
                <div className="external-mapping-list">{selected.mappings.map((mapping,index) => <article key={index}><input aria-label="Campo interno" value={mapping.targetField} onChange={event => updateMapping(index,{ targetField: event.target.value })} placeholder="titulo" /><b>←</b><input aria-label="Campo da API" value={mapping.sourceField} onChange={event => updateMapping(index,{ sourceField: event.target.value })} placeholder="resultado.titulo" /><select aria-label="Tipo" value={mapping.type} onChange={event => updateMapping(index,{ type: event.target.value })}>{TYPES.map(type => <option key={type}>{type}</option>)}</select><button aria-label="Remover campo" onClick={() => updateSelected({ mappings: selected.mappings.filter((_,itemIndex) => itemIndex !== index) })}><LiaTimesSolid /></button></article>)}</div>
                <footer className="external-api-actions"><button className="danger" onClick={removeIntegration}><LiaTrashAltSolid /> Excluir</button><button onClick={test} disabled={!selected.url || testState.loading}><LiaCloudDownloadAltSolid /> {testState.loading ? 'Testando...' : 'Testar leitura'}</button><span><LiaSaveSolid /> Use “Salvar configurações” no topo para publicar.</span></footer>
                {testState.error && <div className="system-firebase-validation error"><LiaExclamationTriangleSolid /> {testState.error}</div>}{testState.data && <div className="external-api-preview"><span><LiaCheckCircleSolid /> Pré-visualização transformada · nenhum dado foi gravado</span><pre>{JSON.stringify(testState.data, null, 2)}</pre></div>}</> : <div className="system-collection-placeholder"><LiaCodeSolid /><strong>Selecione ou crie uma integração</strong><span>Defina a URL e relacione as propriedades externas aos campos internos.</span></div>}</section>
        </div>
    </div>;
};
export default ExternalApiManager;
