import React, { useEffect, useMemo, useState } from 'react';
import { getApp } from 'firebase/app';
import { EmailAuthProvider, reauthenticateWithCredential } from 'firebase/auth';
import { LiaCheckCircleSolid, LiaCloudSolid, LiaDownloadSolid, LiaExclamationTriangleSolid, LiaFireSolid, LiaKeySolid, LiaLockSolid, LiaServerSolid, LiaTimesSolid, LiaUnlockSolid } from 'react-icons/lia';
import { auth } from '../firebase';

const FIELDS = [
    ['apiKey', 'API key', 'REACT_APP_FIREBASE_API_KEY', 'AIza...'],
    ['authDomain', 'Domínio de autenticação', 'REACT_APP_FIREBASE_AUTH_DOMAIN', 'projeto.firebaseapp.com'],
    ['projectId', 'ID do projeto', 'REACT_APP_FIREBASE_PROJECT_ID', 'camara-municipio'],
    ['storageBucket', 'Bucket do Storage', 'REACT_APP_FIREBASE_STORAGE_BUCKET', 'projeto.firebasestorage.app'],
    ['messagingSenderId', 'ID do remetente', 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID', '123456789'],
    ['appId', 'ID do aplicativo web', 'REACT_APP_FIREBASE_APP_ID', '1:123:web:abc'],
    ['measurementId', 'Measurement ID', 'REACT_APP_FIREBASE_MEASUREMENT_ID', 'G-XXXXXXXXXX'],
    ['databaseURL', 'Realtime Database URL', 'REACT_APP_FIREBASE_DATABASE_URL', 'https://projeto-default-rtdb.firebaseio.com'],
    ['functionsBaseUrl', 'URL base das Functions', 'REACT_APP_FUNCTIONS_BASE_URL', 'https://us-central1-projeto.cloudfunctions.net'],
];
const REQUIRED = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId', 'databaseURL'];
const currentConfig = () => { const options = getApp().options; return { apiKey: options.apiKey || '', authDomain: options.authDomain || '', projectId: options.projectId || '', storageBucket: options.storageBucket || '', messagingSenderId: options.messagingSenderId || '', appId: options.appId || '', measurementId: options.measurementId || '', databaseURL: options.databaseURL || '', functionsBaseUrl: process.env.REACT_APP_FUNCTIONS_BASE_URL || '' }; };
const parseFirebaseConfig = value => { const result = {}; FIELDS.forEach(([key, , envName]) => { const jsMatch = value.match(new RegExp(`${key}\\s*:\\s*["']([^"']+)["']`)); const envMatch = value.match(new RegExp(`^${envName}=(.*)$`, 'm')); if (jsMatch?.[1] || envMatch?.[1]) result[key] = (jsMatch?.[1] || envMatch?.[1] || '').trim(); }); return result; };
const buildEnv = config => `${FIELDS.map(([key, , envName]) => `${envName}=${config[key] || ''}`).join('\n')}\n`;
const maskValue = value => { const text = String(value || ''); if (!text) return 'Não configurado'; if (text.length <= 6) return `${text.slice(0, 1)}•••${text.slice(-1)}`; return `${text.slice(0, 3)}${'•'.repeat(Math.min(12, text.length - 6))}${text.slice(-3)}`; };
const blockClipboard = event => event.preventDefault();

const FirebaseSetupWizard = () => {
    const [config, setConfig] = useState(currentConfig); const [paste, setPaste] = useState(''); const [validated, setValidated] = useState(false); const [unlocked, setUnlocked] = useState(false); const [showAuth, setShowAuth] = useState(false); const [password, setPassword] = useState(''); const [authError, setAuthError] = useState(''); const [authenticating, setAuthenticating] = useState(false);
    const missing = useMemo(() => REQUIRED.filter(key => !String(config[key] || '').trim()), [config]); const projectMatches = config.projectId === getApp().options.projectId;
    const importConfig = () => { setConfig(current => ({ ...current, ...parseFirebaseConfig(paste) })); setValidated(false); };
    useEffect(() => { if (!unlocked) return undefined; const timer = setTimeout(() => { setUnlocked(false); setPaste(''); }, 5 * 60 * 1000); return () => clearTimeout(timer); }, [unlocked]);
    const authenticate = async event => { event.preventDefault(); setAuthenticating(true); setAuthError(''); try { const user = auth.currentUser; if (!user?.email) throw new Error('Usuário autenticado não encontrado.'); await reauthenticateWithCredential(user, EmailAuthProvider.credential(user.email, password)); setUnlocked(true); setShowAuth(false); setPassword(''); } catch (error) { setAuthError(error.code === 'auth/invalid-credential' ? 'Senha incorreta.' : 'Não foi possível confirmar a senha desta conta.'); } finally { setAuthenticating(false); } };
    const downloadEnv = () => { if (!unlocked) { setShowAuth(true); return; } const url = URL.createObjectURL(new Blob([buildEnv(config)], { type: 'text/plain;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'firebase.env.local'; anchor.click(); URL.revokeObjectURL(url); };
    return <div className="firebase-setup-wizard">
        <div className="system-firebase-security-bar"><div><LiaLockSolid /><span><strong>Configuração protegida</strong> Os valores mostram somente os três primeiros e os três últimos caracteres.</span></div><button onClick={() => unlocked ? setUnlocked(false) : setShowAuth(true)}>{unlocked ? <><LiaLockSolid /> Bloquear agora</> : <><LiaUnlockSolid /> Desbloquear alterações</>}</button></div>
        <section className="system-firebase-status" onCopy={blockClipboard} onCut={blockClipboard} onContextMenu={blockClipboard}><div><LiaFireSolid /><span>Projeto conectado</span><strong>{maskValue(getApp().options.projectId)}</strong></div><div><LiaKeySolid /><span>Authentication</span><strong>{auth.currentUser ? `Conectado · ${maskValue(auth.currentUser.email)}` : 'Sem sessão ativa'}</strong></div><div><LiaServerSolid /><span>Storage</span><strong>{maskValue(getApp().options.storageBucket)}</strong></div></section>
        <section className="system-firebase-step"><header><b>1</b><div><h3>Crie o projeto no Firebase</h3><p>No console, crie um projeto, adicione um aplicativo Web e habilite Authentication, Firestore, Storage e Realtime Database.</p></div></header><a href="https://console.firebase.google.com/" target="_blank" rel="noreferrer"><LiaCloudSolid /> Abrir Firebase Console</a></section>
        <section className={`system-firebase-step ${!unlocked ? 'locked' : ''}`}><header><b>2</b><div><h3>Cole a configuração do aplicativo Web</h3><p>Confirme sua senha para importar outro projeto Firebase.</p></div></header><textarea value={unlocked ? paste : ''} readOnly={!unlocked} onCopy={blockClipboard} onCut={blockClipboard} onContextMenu={blockClipboard} onChange={event => setPaste(event.target.value)} placeholder={unlocked ? 'Cole o objeto firebaseConfig ou o .env.local' : 'Alterações bloqueadas'} rows="5" /><button onClick={unlocked ? importConfig : () => setShowAuth(true)} disabled={unlocked && !paste.trim()}>{unlocked ? 'Importar configuração' : 'Confirmar senha para importar'}</button></section>
        <section className="system-firebase-step"><header><b>3</b><div><h3>Revise os serviços</h3><p>Para segurança visual, copiar e recortar permanecem desativados mesmo após a reautenticação.</p></div></header><div className={`system-firebase-fields ${!unlocked ? 'masked' : ''}`} onCopy={blockClipboard} onCut={blockClipboard} onContextMenu={blockClipboard}>{FIELDS.map(([key, label, , placeholder]) => <label key={key}><span>{label}{REQUIRED.includes(key) && <em>obrigatório</em>}</span><input readOnly={!unlocked} value={unlocked ? (config[key] || '') : maskValue(config[key])} onChange={event => { if (!unlocked) return; setConfig(current => ({ ...current, [key]: event.target.value.trim() })); setValidated(false); }} placeholder={unlocked ? placeholder : ''} /></label>)}</div><button onClick={unlocked ? () => setValidated(true) : () => setShowAuth(true)}>{unlocked ? 'Validar configuração' : 'Confirmar senha para alterar'}</button>{validated && unlocked && <div className={`system-firebase-validation ${missing.length ? 'error' : 'success'}`}>{missing.length ? <><LiaExclamationTriangleSolid /><span>Preencha: {FIELDS.filter(([key]) => missing.includes(key)).map(([, label]) => label).join(', ')}.</span></> : <><LiaCheckCircleSolid /><span>Configuração completa. {projectMatches ? 'Ela corresponde ao projeto carregado nesta instalação.' : 'Instale o arquivo e reinicie o portal para trocar o projeto.'}</span></>}</div>}</section>
        <section className="system-firebase-step"><header><b>4</b><div><h3>Gere o arquivo da instalação</h3><p>O conteúdo permanece mascarado na tela. O download exige uma confirmação recente da senha.</p></div></header><pre className="system-firebase-env protected" onCopy={blockClipboard} onCut={blockClipboard} onContextMenu={blockClipboard}>{FIELDS.map(([key, , envName]) => `${envName}=${maskValue(config[key])}`).join('\n')}</pre><div className="system-firebase-actions"><button onClick={downloadEnv}><LiaDownloadSolid /> {unlocked ? 'Baixar arquivo' : 'Confirmar senha para baixar'}</button></div></section>
        <section className="system-firebase-step"><header><b>5</b><div><h3>Publique a infraestrutura</h3><p>Autentique o Firebase CLI no servidor e execute os comandos abaixo.</p></div></header><pre className="system-firebase-commands">firebase login{`\n`}firebase use --add{`\n`}firebase deploy --only firestore:rules,firestore:indexes,storage,database{`\n`}firebase deploy --only functions{`\n`}firebase deploy --only hosting</pre><div className="system-readonly-note"><LiaExclamationTriangleSolid /><div><strong>Credenciais administrativas ficam no servidor</strong><span>Secrets de e-mail, YouTube, APIs e contas de serviço devem ficar no Google Secret Manager ou nas variáveis protegidas da hospedagem.</span></div></div></section>
        {showAuth && <div className="modal-overlay system-reauth-overlay" onMouseDown={event => event.target === event.currentTarget && setShowAuth(false)}><form className="modal-content system-reauth-modal" onSubmit={authenticate}><div className="modal-header"><div><small>Confirmação de segurança</small><h3>Digite sua senha</h3></div><button type="button" className="modal-close-btn" onClick={() => setShowAuth(false)}><LiaTimesSolid /></button></div><p>Confirme a senha de <strong>{maskValue(auth.currentUser?.email)}</strong> para liberar alterações por cinco minutos.</p><label><span>Senha atual</span><input autoFocus type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required /></label>{authError && <div className="system-firebase-validation error"><LiaExclamationTriangleSolid /> {authError}</div>}<footer><button type="button" className="btn-secondary" onClick={() => setShowAuth(false)}>Cancelar</button><button className="btn-primary" disabled={authenticating}>{authenticating ? 'Confirmando...' : 'Confirmar senha'}</button></footer></form></div>}
    </div>;
};
export default FirebaseSetupWizard;
