import React, { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot, updateDoc, doc } from 'firebase/firestore';
import { LiaCheckCircleSolid, LiaPauseCircleSolid, LiaTimesSolid, LiaUserClockSolid } from 'react-icons/lia';
import { firestore, auth } from '../firebase';

const ReceptionQueueModal = ({ onClose }) => {
    const [tickets, setTickets] = useState([]); const [error, setError] = useState(''); const [loadingId, setLoadingId] = useState('');
    useEffect(() => onSnapshot(collection(firestore, 'atendimento-fila'), snap => setTickets(snap.docs.map(item => ({ id: item.id, ...item.data() }))), err => setError(err?.code === 'permission-denied' ? 'Seu usuário não tem permissão para consultar a fila.' : 'Não foi possível carregar a fila.')), []);
    const queue = useMemo(() => tickets.filter(item => ['Aguardando', 'Chamando', 'Em Atendimento'].includes(item.status)).sort((a, b) => Number(Boolean(b.prioridade)) - Number(Boolean(a.prioridade))), [tickets]);
    const changeTicket = async (ticket, updates) => { setLoadingId(ticket.id); try { await updateDoc(doc(firestore, 'atendimento-fila', ticket.id), { ...updates, atualizadoEm: new Date(), atualizadoPor: auth.currentUser?.email || 'Recepção' }); } catch (err) { setError(err?.code === 'permission-denied' ? 'Sem permissão para alterar esta senha.' : 'Não foi possível alterar a senha.'); } finally { setLoadingId(''); } };
    return <div className="modal-overlay" onClick={onClose}><div className="modal-content reception-queue-modal" onClick={event => event.stopPropagation()}><div className="modal-header"><div><small>Operação da recepção</small><h2>Fila de atendimentos</h2><p>Priorize, confirme ou cancele as senhas.</p></div><button type="button" className="modal-close-btn" onClick={onClose}><LiaTimesSolid /></button></div>{error && <p className="queue-counter-feedback error" role="alert">{error}</p>}<div className="reception-queue-summary"><span><b>{queue.filter(item => item.prioridade).length}</b> prioritários</span><span><b>{queue.filter(item => !item.prioridade).length}</b> normais</span><strong>{queue.length} na fila</strong></div><div className="reception-queue-list">{queue.length === 0 && <p className="queue-empty">Nenhum atendimento ativo.</p>}{queue.map(ticket => <article key={ticket.id} className={`${ticket.prioridade ? 'priority ' : ''}${ticket.status === 'Chamando' ? 'calling' : ''}`}><strong>{ticket.senha}</strong><div><b>{ticket.nome || 'Cidadão'}</b><span>{ticket.assunto || ticket.setor || 'Atendimento'} · {ticket.status}</span></div><div className="reception-queue-actions"><button type="button" disabled={loadingId === ticket.id} title={ticket.prioridade ? 'Retirar prioridade' : 'Priorizar atendimento'} onClick={() => changeTicket(ticket, { prioridade: !ticket.prioridade })}><LiaUserClockSolid /></button>{ticket.status === 'Aguardando' && <button type="button" disabled={loadingId === ticket.id} title="Confirmar chamada" onClick={() => changeTicket(ticket, { status: 'Chamando', chamadoEm: new Date() })}><LiaCheckCircleSolid /></button>}<button type="button" disabled={loadingId === ticket.id} title="Cancelar atendimento" onClick={() => changeTicket(ticket, { status: 'Cancelado', canceladoEm: new Date(), motivoCancelamento: 'Cancelado pela recepção' })}><LiaPauseCircleSolid /></button></div></article>)}</div></div></div>;
};
export default ReceptionQueueModal;
